scram::Error Class Reference
scram::Error Class Reference
The Error class is the base class for common exceptions specific to the SCRAM code.
#include <error.h>
Public Member Functions
Error (std::string msg)
Constructs a new error with a provided message.
Error (const Error &)=default
Explicit declaration.
const char * what () const noexceptoverride
const std::string & msg () const
void msg (std::string msg)
Sets the error messages.
Detailed Description
The Error class is the base class for common exceptions specific to the SCRAM code.
Definition at line 31 of file error.h.
Constructor & Destructor Documentation
scram::Error::Error (std::string msg) explicit
Constructs a new error with a provided message.
Parameters
[in] msg The message to be passed with this error.
Definition at line 27 of file error.cc.
Member Function Documentation
const char * scram::Error::what () const override noexcept
Returns
The formatted error message to be printed.
Definition at line 31 of file error.cc.
const std::string& scram::Error::msg () const inline
Returns
The core message describing the error.
Definition at line 46 of file error.h.
Referenced by scram::Config::Config(), scram::mef::Initializer::Initializer(), and scram::mef::Initializer::Extractor< Histogram,-1 >::operator()().
void scram::Error::msg (std::string msg) inline
Sets the error messages.
Parameters
[in] msg The error message.
Definition at line 51 of file error.h.
The documentation for this class was generated from the following files:
error.h
error.cc