scram::mef::Initializer Class Reference
scram::mef::Initializer Class Reference
This class operates on input files to initialize analysis constructs like models, fault trees, and events.
#include <initializer.h>
Classes
struct Extractor
struct Extractor< Histogram,-1 >
Full specialization for Extractor of Histogram expressions.
struct Extractor< T, 0 >
Partial specialization for terminal Extractor.
struct Extractor< T,-1 >
Specialization of Extractor to extract all expressions into arg vector.
Public Member Functions
Initializer (const std::vector< std::string > &xml_files, core::Settings settings)
Reads input files with the structure of analysis constructs.
std::shared_ptr< Model > model () const
Detailed Description
This class operates on input files to initialize analysis constructs like models, fault trees, and events.
The initialization phase includes validation and proper setup of the constructs for future use or analysis.
Definition at line 52 of file initializer.h.
Constructor & Destructor Documentation
scram::mef::Initializer::Initializer (const std::vector< std::string > & xml_files, core::Settings settings)
Reads input files with the structure of analysis constructs.
Initializes the analysis model from the given input files. Puts all events into their appropriate containers in the model.
Parameters
[in] xml_files The MEF XML input files.
[in] settings Analysis settings.
Exceptions
DuplicateArgumentError Input contains duplicate files.
ValidationError The input contains errors.
IOError One of the input files is not accessible.
Definition at line 65 of file initializer.cc.
References scram::mef::Formula::AddArgument(), scram::mef::Element::AddAttribute(), scram::mef::Component::AddBasicEvent(), scram::mef::Component::AddCcfGroup(), scram::mef::Component::AddComponent(), scram::mef::Component::AddGate(), scram::mef::Component::AddHouseEvent(), scram::mef::Component::AddParameter(), scram::mef::Role::base_path(), begin, CLOCK, scram::ConstructDomParser(), scram::DEBUG1, scram::DEBUG2, DUR, scram::mef::Parameter::expression(), scram::mef::BasicEvent::expression(), scram::mef::Gate::formula(), scram::GetAttributeValue(), scram::GetContent(), scram::Env::input_schema(), scram::mef::kNumUnits, scram::mef::kOperatorToString, scram::mef::kUnitsToString, scram::mef::Element::label(), LOG, scram::Error::msg(), scram::mef::Role::role(), scram::mef::Gate::Validate(), and scram::XmlElement().
Member Function Documentation
std::shared_ptr<Model> scram::mef::Initializer::model () const inline
Returns
The model built from the input files.
Definition at line 68 of file initializer.h.
Referenced by scram::mef::Initializer::Extractor< Histogram,-1 >::operator()().
The documentation for this class was generated from the following files:
initializer.h
initializer.cc