scram::mef::CcfGroup Class Reference
scram::mef::CcfGroup Class Reference abstract
Abstract base class for all common cause failure models.
#include <ccf_group.h>
Public Member Functions
CcfGroup (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructor to be used by derived classes.
const ElementTable< BasicEventPtr > & members () const
void AddMember (const BasicEventPtr &basic_event)
Adds a basic event into this CCF group.
void AddDistribution (const ExpressionPtr &distr)
Adds the distribution that describes the probability of basic events in this CCF group.
void AddFactor (const ExpressionPtr &factor, int level)
Adds a CCF factor for the specified model.
void ValidateDistribution ()
Checks if the provided distribution is between 0 and 1.
virtual void Validate () const
Validates the setup for the CCF model and group.
void ApplyModel ()
Processes the given factors and members to create common cause failure probabilities and new events that can replace the members in a fault tree.
Public Member Functions inherited from scram::mef::Element
Element (std::string name, bool optional_name=false)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string new_label)
Sets the label.
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Public Member Functions inherited from scram::mef::Id
Id (const Element &el, const Role &role)
Mangles the element name to be unique.
const std::string & id () const
Protected Types
using ExpressionMap = std::vector< std::pair< int, ExpressionPtr >>
Mapping expressions and their application levels.
Protected Member Functions
const ExpressionPtr & distribution () const
const ExpressionMap & factors () const
Detailed Description
Abstract base class for all common cause failure models.
Definition at line 43 of file ccf_group.h.
Constructor & Destructor Documentation
scram::mef::CcfGroup::CcfGroup (std::string name, std::string base_path = "", RoleSpecifier role = RoleSpecifier::kPublic) explicit
Constructor to be used by derived classes.
Parameters
[in] name The name of a CCF group.
[in] base_path The series of containers to get this group.
[in] role The role of the CCF group within the model or container.
Exceptions
LogicError The name is empty.
Definition at line 31 of file ccf_group.cc.
Member Function Documentation
const ElementTable<BasicEventPtr>& scram::mef::CcfGroup::members () const inline
Returns
Members of the CCF group with original names as keys.
Definition at line 61 of file ccf_group.h.
References AddDistribution(), and AddMember().
Referenced by ApplyModel(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
void scram::mef::CcfGroup::AddMember (const BasicEventPtr & basic_event)
Adds a basic event into this CCF group.
This function asserts that each basic event has unique string id.
Parameters
[in] basic_event A member basic event.
Exceptions
DuplicateArgumentError The basic event is already in the group.
IllegalOperation The probability distribution for this CCF group is already defined. No more members are accepted.
Definition at line 36 of file ccf_group.cc.
References scram::mef::Element::name().
Referenced by members(), and scram::mef::Initializer::Extractor< Histogram,-1 >::operator()().
void scram::mef::CcfGroup::AddDistribution (const ExpressionPtr & distr)
Adds the distribution that describes the probability of basic events in this CCF group.
All basic events should be added as members before defining their probabilities. No more basic events can be added after this function.
Parameters
[in] distr The probability distribution of this group.
Exceptions
LogicError The distribution has already been defined.
Definition at line 48 of file ccf_group.cc.
References scram::mef::Element::name().
Referenced by members(), and scram::mef::Initializer::Extractor< Histogram,-1 >::operator()().
void scram::mef::CcfGroup::AddFactor (const ExpressionPtr & factor, int level) inline
Adds a CCF factor for the specified model.
The addition of factors must be in ascending level order and no gaps are allowed between levels. The default case is to start from 1.
Parameters
[in] factor A factor for the CCF model.
[in] level The level of the passed factor.
Exceptions
ValidationError Level is not what is expected.
LogicError The level is not positive.
Definition at line 95 of file ccf_group.h.
References ApplyModel(), Validate(), and ValidateDistribution().
Referenced by scram::mef::Initializer::Extractor< Histogram,-1 >::operator()().
void scram::mef::CcfGroup::ValidateDistribution ()
Checks if the provided distribution is between 0 and 1.
This check must be performed before validating basic events that are members of this CCF group to give more precise error messages.
Exceptions
ValidationError There is an issue with the distribution.
Definition at line 67 of file ccf_group.cc.
References scram::mef::Element::name().
Referenced by AddFactor().
void scram::mef::CcfGroup::Validate () const virtual
Validates the setup for the CCF model and group.
The passed expressions must be checked for circular logic before initiating the CCF validation.
Exceptions
ValidationError There is an issue with the setup.
Reimplemented in scram::mef::PhiFactorModel.
Definition at line 74 of file ccf_group.cc.
References scram::mef::Element::name().
Referenced by AddFactor(), and scram::mef::PhiFactorModel::Validate().
void scram::mef::CcfGroup::ApplyModel ()
Processes the given factors and members to create common cause failure probabilities and new events that can replace the members in a fault tree.
Definition at line 160 of file ccf_group.cc.
References distribution(), factors(), scram::mef::ConstantExpression::kOne, members(), and scram::mef::Element::name().
Referenced by AddFactor().
const ExpressionPtr& scram::mef::CcfGroup::distribution () const inline protected
Returns
The probability distribution of the events.
Definition at line 125 of file ccf_group.h.
Referenced by ApplyModel(), and scram::mef::PhiFactorModel::Validate().
const ExpressionMap& scram::mef::CcfGroup::factors () const inline protected
Returns
CCF factors of the model.
Definition at line 128 of file ccf_group.h.
Referenced by ApplyModel(), and scram::mef::PhiFactorModel::Validate().
The documentation for this class was generated from the following files:
ccf_group.h
ccf_group.cc