scram::mef::ExponentialExpression Class Reference
scram::mef::ExponentialExpression Class Reference
Negative exponential distribution with hourly failure rate and time.
#include <exponential.h>
Public Member Functions
ExponentialExpression (const ExpressionPtr &lambda, const ExpressionPtr &t)
Constructor for exponential expression with two arguments.
void Validate () const override
double Mean () noexceptoverride
double Max () noexceptoverride
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args)
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual bool IsConstant () noexcept
Determines if the value of the expression varies.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
Negative exponential distribution with hourly failure rate and time.
Definition at line 34 of file exponential.h.
Constructor & Destructor Documentation
scram::mef::ExponentialExpression::ExponentialExpression (const ExpressionPtr & lambda, const ExpressionPtr & t)
Constructor for exponential expression with two arguments.
Parameters
[in] lambda Hourly rate of failure.
[in] t Mission time in hours.
Definition at line 28 of file exponential.cc.
Member Function Documentation
void scram::mef::ExponentialExpression::Validate () const override virtual
Exceptions
InvalidArgument The failure rate or time is negative.
Reimplemented from scram::mef::Expression.
Definition at line 34 of file exponential.cc.
References scram::mef::Expression::Mean(), and scram::mef::Expression::Min().
double scram::mef::ExponentialExpression::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 45 of file exponential.h.
References scram::mef::Expression::Mean().
double scram::mef::ExponentialExpression::Max () inline override virtual noexcept
Returns
Maximum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 49 of file exponential.h.
References scram::mef::Expression::Max().
double scram::mef::ExponentialExpression::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 53 of file exponential.h.
References scram::mef::Expression::Min(), and scram::mef::Expression::Sample().
The documentation for this class was generated from the following files:
exponential.h
exponential.cc