scram::Random Class Reference
scram::Random Class Reference
This class contains generators for various random distributions.
#include <random.h>
Static Public Member Functions
static void seed (int seed) noexcept
Sets the seed of the underlying random number generator.
static double UniformRealGenerator (double lower, double upper) noexcept
RNG from a uniform distribution.
static double TriangularGenerator (double lower, double mode, double upper) noexcept
RNG from a triangular distribution.
template<class IteratorB , class IteratorW >
static double PiecewiseLinearGenerator (IteratorB first_b, IteratorB last_b, IteratorW first_w) noexcept
RNG from a piecewise linear distribution.
template<class IteratorB , class IteratorW >
static double HistogramGenerator (IteratorB first_b, IteratorB last_b, IteratorW first_w) noexcept
RNG from a histogram distribution.
template<class Iterator >
static int DiscreteGenerator (Iterator first1, Iterator last1) noexcept
RNG from a discrete distribution.
static int BinomialGenerator (int n, double p) noexcept
RNG from a Binomial distribution.
static double NormalGenerator (double mean, double sigma) noexcept
RNG from a normal distribution.
static double LogNormalGenerator (double m, double s) noexcept
RNG from a lognormal distribution.
static double GammaGenerator (double k, double theta) noexcept
RNG from a Gamma distribution.
static double BetaGenerator (double alpha, double beta) noexcept
RNG from a Beta distribution.
static double WeibullGenerator (double k, double lambda) noexcept
RNG from a Weibull distribution.
static double ExponentialGenerator (double lambda) noexcept
RNG from an Exponential distribution.
static int PoissonGenerator (int mean) noexcept
RNG from a Poisson distribution.
static double LogUniformGenerator (double lower, double upper) noexcept
RNG from a log-uniform distribution.
static double LogTriangularGenerator (double lower, double mode, double upper) noexcept
RNG from a log-triangular distribution.
Detailed Description
This class contains generators for various random distributions.
The values passed to the member functions are asserted to be in the correct form. In other words, the user should make sure that the passed parameters are valid. For example, standard deviation cannot be negative.
This facility wraps the engine and distributions. It provides convenience and reproducibility for the whole analysis.
Definition at line 43 of file random.h.
Member Function Documentation
static void scram::Random::seed (int seed) inline static noexcept
Sets the seed of the underlying random number generator.
Parameters
[in] seed The seed for RNGs.
Definition at line 48 of file random.h.
Referenced by scram::core::RiskAnalysis::Analyze().
static double scram::Random::UniformRealGenerator (double lower, double upper) inline static noexcept
RNG from a uniform distribution.
Parameters
[in] lower Lower bound.
[in] upper Upper bound.
Returns
A sampled value.
Definition at line 58 of file random.h.
Referenced by LogUniformGenerator(), and scram::mef::UniformDeviate::Validate().
static double scram::Random::TriangularGenerator (double lower, double mode, double upper) inline static noexcept
RNG from a triangular distribution.
Parameters
[in] lower Lower bound.
[in] mode The peak of the distribution.
[in] upper Upper bound.
Returns
A sampled value.
Definition at line 70 of file random.h.
Referenced by LogTriangularGenerator().
template<class IteratorB , class IteratorW > static double scram::Random::PiecewiseLinearGenerator (IteratorB first_b, IteratorB last_b, IteratorW first_w) inline static noexcept
RNG from a piecewise linear distribution.
Template Parameters
IteratorB Input iterator of interval boundaries returning double.
IteratorW Input iterator of weights returning double.
Parameters
[in] first_b The begin of the interval boundaries.
[in] last_b The sentinel end of the interval boundaries.
[in] first_w The begin of the interval weights.
Returns
A sampled value.
Precondition
Interval points for the distribution must be strictly increasing.
The number of weights must be equal to the number of intervals (boundaries - 1). Extra weights are ignored.
Definition at line 94 of file random.h.
template<class IteratorB , class IteratorW > static double scram::Random::HistogramGenerator (IteratorB first_b, IteratorB last_b, IteratorW first_w) inline static noexcept
RNG from a histogram distribution.
Template Parameters
IteratorB Input iterator of interval boundaries returning double.
IteratorW Input iterator of weights returning double.
Parameters
[in] first_b The begin of the interval boundaries.
[in] last_b The sentinel end of the interval boundaries.
[in] first_w The begin of the interval weights.
Returns
A sampled value from the interval.
Precondition
Interval points for the distribution must be strictly increasing.
The number of weights must be equal to the number of intervals (boundaries - 1). Extra weights are ignored.
Definition at line 116 of file random.h.
Referenced by scram::mef::Histogram::Mean().
template<class Iterator > static int scram::Random::DiscreteGenerator (Iterator first1, Iterator last1) inline static noexcept
RNG from a discrete distribution.
Template Parameters
Iterator Input iterator of weights returning double.
Parameters
[in] first1 The begin of the interval weights.
[in] last1 The sentinel end of the interval weights.
Returns
Integer in the range [0, n).
Definition at line 131 of file random.h.
static int scram::Random::BinomialGenerator (int n, double p) inline static noexcept
RNG from a Binomial distribution.
Parameters
[in] n Number of trials.
[in] p Probability of success.
Returns
The number of successes.
Definition at line 141 of file random.h.
static double scram::Random::NormalGenerator (double mean, double sigma) inline static noexcept
RNG from a normal distribution.
Parameters
[in] mean The mean of the distribution.
[in] sigma The standard deviation of the distribution.
Returns
A sampled value.
Definition at line 151 of file random.h.
Referenced by scram::mef::NormalDeviate::Validate().
static double scram::Random::LogNormalGenerator (double m, double s) inline static noexcept
RNG from a lognormal distribution.
Parameters
[in] m The m location parameter of the distribution.
[in] s The s scale factor of the distribution.
Returns
A sampled value.
Definition at line 162 of file random.h.
Referenced by scram::mef::LogNormalDeviate::Validate().
static double scram::Random::GammaGenerator (double k, double theta) inline static noexcept
RNG from a Gamma distribution.
Parameters
[in] k Shape parameter of Gamma distribution.
[in] theta Scale parameter of Gamma distribution.
Returns
A sampled value.
Note
The rate parameter is 1/theta, so for alpha/beta system, pass 1/beta as a second parameter for this generator.
Definition at line 177 of file random.h.
Referenced by scram::mef::GammaDeviate::Max().
static double scram::Random::BetaGenerator (double alpha, double beta) inline static noexcept
RNG from a Beta distribution.
Parameters
[in] alpha Alpha shape parameter of Beta distribution.
[in] beta Beta shape parameter of Beta distribution.
Returns
A sampled value.
Definition at line 189 of file random.h.
Referenced by scram::mef::BetaDeviate::Max().
static double scram::Random::WeibullGenerator (double k, double lambda) inline static noexcept
RNG from a Weibull distribution.
Parameters
[in] k Shape parameter of Weibull distribution.
[in] lambda Scale parameter of Weibull distribution.
Returns
A sampled value.
Definition at line 201 of file random.h.
static double scram::Random::ExponentialGenerator (double lambda) inline static noexcept
RNG from an Exponential distribution.
Parameters
[in] lambda Rate parameter of Exponential distribution.
Returns
A sampled value.
Definition at line 212 of file random.h.
static int scram::Random::PoissonGenerator (int mean) inline static noexcept
RNG from a Poisson distribution.
Parameters
[in] mean The mean value for Poisson distribution.
Returns
A sampled value.
Definition at line 222 of file random.h.
static double scram::Random::LogUniformGenerator (double lower, double upper) inline static noexcept
RNG from a log-uniform distribution.
Parameters
[in] lower Lower bound.
[in] upper Upper bound.
Returns
A sampled value.
Definition at line 233 of file random.h.
References UniformRealGenerator().
static double scram::Random::LogTriangularGenerator (double lower, double mode, double upper) inline static noexcept
RNG from a log-triangular distribution.
Parameters
[in] lower Lower bound.
[in] mode The peak of the distribution.
[in] upper Upper bound.
Returns
A sampled value.
Definition at line 244 of file random.h.
References TriangularGenerator().
The documentation for this class was generated from the following files:
random.h
random.cc