scram::core::Preprocessor Class Reference
scram::core::Preprocessor Class Reference abstract
The class provides main preprocessing operations over a Boolean graph to simplify the fault tree and to help analysis run more efficiently.
#include <preprocessor.h>
Classes
class DecompositionProcessor
Functor for processing of decomposition setups with common nodes.
class GateSet
Container of unique gates.
struct MergeTable
Helper struct for algorithms that must make an optimal decision how to merge or factor out common arguments of gates into new gates.
Public Member Functions
Preprocessor (BooleanGraph *graph) noexcept
Constructs a preprocessor of a Boolean graph representing a fault tree.
virtual void Run () noexcept=0
Runs the default preprocessing that achieves the graph in a normal form.
Protected Member Functions
void RunPhaseOne () noexcept
Container of unique gates by semantics.
void RunPhaseTwo () noexcept
Preprocessing phase of the original structure of the graph.
void RunPhaseThree () noexcept
Application of gate normalization.
void RunPhaseFour () noexcept
Propagation of complements.
void RunPhaseFive () noexcept
The final phase that cleans up the graph, and puts the structure of the graph ready for analysis.
bool CheckRootGate () noexcept
Checks the root gate of the graph for further processing.
void RemoveNullGates () noexcept
Removes argument gates of NULL type, which means these arg gates have only one argument.
void RemoveConstants () noexcept
Removes all Boolean constants from the Boolean graph according to the Boolean logic of the gates.
void PropagateConstant (const ConstantPtr &constant) noexcept
Propagates a Boolean constant bottom-up.
void PropagateConstant (const GatePtr &gate) noexcept
Propagates constant gates bottom-up.
void PropagateNullGate (const GatePtr &gate) noexcept
Propagate NULL type gates bottom-up.
void ClearConstGates () noexcept
Clears all constant gates registered for removal by algorithms or other preprocessing functions.
void ClearNullGates () noexcept
Clears all NULL type gates registered for removal by algorithms or other preprocessing functions.
void NormalizeGates (bool full) noexcept
Normalizes the gates of the whole Boolean graph into OR, AND gates.
void NotifyParentsOfNegativeGates (const GatePtr &gate) noexcept
Notifies all parents of negative gates, such as NOT, NOR, and NAND, before transforming these gates into basic gates of OR and AND.
void NormalizeGate (const GatePtr &gate, bool full) noexcept
Normalizes complex gates into OR, AND gates.
void NormalizeXorGate (const GatePtr &gate) noexcept
Normalizes a gate with XOR logic.
void NormalizeVoteGate (const GatePtr &gate) noexcept
Normalizes a VOTE gate with a vote number.
void PropagateComplements (const GatePtr &gate, bool keep_modules, std::unordered_map< int, GatePtr > *complements) noexcept
Propagates complements of argument gates down to leafs according to the De Morgan's law in order to remove any negative logic from the graph's gates.
bool CoalesceGates (bool common) noexcept
Runs gate coalescence on the whole Boolean graph.
bool CoalesceGates (const GatePtr &gate, bool common) noexcept
Coalesces positive argument gates with the same OR or AND logic as parents.
bool ProcessMultipleDefinitions () noexcept
Detects and replaces multiple definitions of gates.
void DetectMultipleDefinitions (const GatePtr &gate, std::unordered_map< GatePtr, std::vector< GateWeakPtr >> *multi_def, GateSet *unique_gates) noexcept
Traverses the Boolean graph to collect multiple definitions of gates.
void DetectModules () noexcept
Traverses the Boolean graph to detect modules.
int AssignTiming (int time, const GatePtr &gate) noexcept
Traverses the given gate and assigns time of visit to nodes.
void FindModules (const GatePtr &gate) noexcept
Determines modules from original gates that have been already timed.
void ProcessModularArgs (const GatePtr &gate, const std::vector< std::pair< int, NodePtr >> &non_shared_args, std::vector< std::pair< int, NodePtr >> *modular_args, std::vector< std::pair< int, NodePtr >> *non_modular_args) noexcept
Processes gate arguments found during the module detection.
GatePtr CreateNewModule (const GatePtr &gate, const std::vector< std::pair< int, NodePtr >> &args) noexcept
Creates a new module as an argument of an existing gate if the logic of the existing parent gate allows a sub-module.
void FilterModularArgs (std::vector< std::pair< int, NodePtr >> *modular_args, std::vector< std::pair< int, NodePtr >> *non_modular_args) noexcept
Checks if a group of modular arguments share anything with non-modular arguments.
void GroupModularArgs (std::vector< std::pair< int, NodePtr >> *modular_args, std::vector< std::vector< std::pair< int, NodePtr >>> *groups) noexcept
Groups modular arguments by their common elements.
void CreateNewModules (const GatePtr &gate, const std::vector< std::pair< int, NodePtr >> &modular_args, const std::vector< std::vector< std::pair< int, NodePtr >>> &groups) noexcept
Creates new module gates from groups of modular arguments if the logic of the parent gate allows sub-modules.
std::vector< GateWeakPtr > GatherModules () noexcept
Gathers all modules in the Boolean graph.
bool MergeCommonArgs () noexcept
Identifies common arguments of gates, and merges the common arguments into new gates.
bool MergeCommonArgs (Operator op) noexcept
Merges common arguments for a specific group of gates.
void MarkCommonArgs (const GatePtr &gate, Operator op) noexcept
Marks common arguments of gates with a specific operator.
void GatherCommonArgs (const GatePtr &gate, Operator op, MergeTable::Candidates *group) noexcept
Gathers common arguments of the gates in the group of a specific operator.
void FilterMergeCandidates (MergeTable::Candidates *candidates) noexcept
Filters merge candidates and their shared arguments to detect opportunities for simplifications like gate substitutions.
void GroupCandidatesByArgs (MergeTable::Candidates *candidates, std::vector< MergeTable::Candidates > *groups) noexcept
Groups candidates with common arguments.
void GroupCommonParents (int num_common_args, const MergeTable::Candidates &group, MergeTable::Collection *parents) noexcept
Finds intersections of common arguments of gates.
void GroupCommonArgs (const MergeTable::Collection &options, MergeTable *table) noexcept
Groups common args for merging.
void FindOptionGroup (MergeTable::MergeGroup *all_options, MergeTable::OptionGroup *best_group) noexcept
Finds an optimal way of grouping options.
void FindBaseOption (MergeTable::MergeGroup *all_options, MergeTable::MergeGroup::iterator *best_option) noexcept
Finds the starting option for group formation.
void TransformCommonArgs (MergeTable::MergeGroup *group) noexcept
Transforms common arguments of gates into new gates.
bool DetectDistributivity () noexcept
Detects and manipulates AND and OR gate distributivity for the whole graph.
bool DetectDistributivity (const GatePtr &gate) noexcept
Detects and manipulates AND and OR gate distributivity.
bool HandleDistributiveArgs (const GatePtr &gate, Operator distr_type, std::vector< GatePtr > *candidates) noexcept
Manipulates gates with distributive arguments.
bool FilterDistributiveArgs (const GatePtr &gate, std::vector< GatePtr > *candidates) noexcept
Detects relationships between the gate and its distributive arguments to remove unnecessary candidates.
void GroupDistributiveArgs (const MergeTable::Collection &options, MergeTable *table) noexcept
Groups distributive gate arguments for future factorization.
void TransformDistributiveArgs (const GatePtr &gate, Operator distr_type, MergeTable::MergeGroup *group) noexcept
Transforms distributive of arguments gates into a new subgraph.
void BooleanOptimization () noexcept
Propagates failures of common nodes to detect redundancy.
void GatherCommonNodes (std::vector< GateWeakPtr > *common_gates, std::vector< std::weak_ptr< Variable >> *common_variables) noexcept
Traverses the graph to find nodes that have more than one parent.
template<class N >
void ProcessCommonNode (const std::weak_ptr< N > &common_node) noexcept
Tries to simplify the graph by removing redundancies generated by a common node.
void MarkAncestors (const NodePtr &node, GatePtr *module) noexcept
Marks ancestor gates true.
int PropagateState (const GatePtr &gate, const NodePtr &node) noexcept
Propagates failure or success of a common node by setting its ancestors' optimization values to 1 or -1 if they fail or succeed according to their Boolean logic.
void DetermineGateState (const GatePtr &gate, int num_failure, int num_success) noexcept
Determines if a gate fails or succeeds due to failed/succeeded arguments.
int CollectStateDestinations (const GatePtr &gate, int index, std::unordered_map< int, GateWeakPtr > *destinations) noexcept
Collects failure or success destinations and marks non-redundant nodes.
void CollectRedundantParents (const NodePtr &node, std::unordered_map< int, GateWeakPtr > *destinations, std::vector< GateWeakPtr > *redundant_parents) noexcept
Detects if parents of a node are redundant.
void ProcessRedundantParents (const NodePtr &node, const std::vector< GateWeakPtr > &redundant_parents) noexcept
Detects if parents of a node are redundant.
template<class N >
void ProcessStateDestinations (const std::shared_ptr< N > &node, const std::unordered_map< int, GateWeakPtr > &destinations) noexcept
Transforms failure or success destination according to the logic and the common node.
void ClearStateMarks (const GatePtr &gate) noexcept
Clears all the ancestor marks used in Boolean optimization steps.
bool DecomposeCommonNodes () noexcept
The Shannon decomposition for common nodes in the Boolean graph.
void MarkCoherence () noexcept
Marks coherence of the whole graph.
void MarkCoherence (const GatePtr &gate) noexcept
Marks gates with coherence flags.
void ReplaceGate (const GatePtr &gate, const GatePtr &replacement) noexcept
Replaces one gate in the graph with another.
bool RegisterToClear (const GatePtr &gate) noexcept
Registers mutated gates for potential deletion later.
void AssignOrder () noexcept
Assigns order for Boolean graph variables.
int TopologicalOrder (Gate *root, int order) noexcept
Assigns topological ordering to nodes of the Boolean Graph.
template<class T >
std::vector< T * > OrderArguments (const Gate &gate) noexcept
Determines the order of traversal for gate arguments.
void GatherNodes (std::vector< GatePtr > *gates, std::vector< VariablePtr > *variables) noexcept
Gathers all nodes in the Boolean graph.
void GatherNodes (const GatePtr &gate, std::vector< GatePtr > *gates, std::vector< VariablePtr > *variables) noexcept
Gathers nodes in the sub-graph.
const BooleanGraph & graph () const
Detailed Description
The class provides main preprocessing operations over a Boolean graph to simplify the fault tree and to help analysis run more efficiently.
Definition at line 43 of file preprocessor.h.
Constructor & Destructor Documentation
scram::core::Preprocessor::Preprocessor (BooleanGraph * graph) explicit noexcept
Constructs a preprocessor of a Boolean graph representing a fault tree.
Parameters
[in] graph The Boolean graph to be preprocessed.
Warning
There should not be another shared pointer to the root gate outside of the passed Boolean graph. Upon preprocessing a new root gate may be assigned to the graph, and, if there is an extra pointer to the previous top gate outside of the graph, the destructor will not be called as expected by the preprocessing algorithms, which will mess the new structure of the Boolean graph.
Definition at line 92 of file preprocessor.cc.
Member Function Documentation
void scram::core::Preprocessor::Run () pure virtual noexcept
Runs the default preprocessing that achieves the graph in a normal form.
Implemented in scram::core::CustomPreprocessor< Mocus >, scram::core::CustomPreprocessor< Zbdd >, and scram::core::CustomPreprocessor< Bdd >.
Definition at line 96 of file preprocessor.cc.
References CheckRootGate(), CLOCK, scram::DEBUG2, DUR, LOG, scram::core::BooleanGraph::normal(), RunPhaseOne(), RunPhaseThree(), and RunPhaseTwo().
Referenced by scram::core::FaultTreeAnalyzer< Algorithm >::Analyze(), scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), scram::core::CustomPreprocessor< Bdd >::Run(), and scram::core::CustomPreprocessor< Zbdd >::Run().
void scram::core::Preprocessor::RunPhaseOne () protected noexcept
Container of unique gates by semantics.
The initial phase of preprocessing. The most basic cleanup algorithms are applied. The cleanup should benefit all other phases and algorithms.
Note
The constants or house events in the graph are cleaned. Any constant state gates must be removed by the future preprocessing algorithms as they introduce these constant state gates.
NULL type (pass-through) gates are processed. Any NULL type gates must be processed and removed by the future preprocessing algorithms as they introduce these NULL type gates.
Warning
This phase also runs partial normalization of gates; however, the preprocessing algorithms should not rely on this. If the partial normalization messes some significant algorithm, it may be removed from this phase in future.
Definition at line 256 of file preprocessor.cc.
References CheckRootGate(), scram::DEBUG3, LOG, NormalizeGates(), RemoveConstants(), RemoveNullGates(), and SANITY_ASSERT.
Referenced by Run().
void scram::core::Preprocessor::RunPhaseTwo () protected noexcept
Preprocessing phase of the original structure of the graph.
This phase attempts to leverage the existing information from the structure of the graph to maximize the optimization and to make the preprocessing techniques efficient.
Note
Multiple definitions of gates are detected and processed.
Modules are detected and created.
Non-module and non-multiple gates are coalesced.
Boolean optimization is applied.
Definition at line 280 of file preprocessor.cc.
References BooleanOptimization(), CheckRootGate(), CLOCK, CoalesceGates(), scram::DEBUG3, DecomposeCommonNodes(), DetectDistributivity(), DetectModules(), DUR, LOG, MergeCommonArgs(), ProcessMultipleDefinitions(), and SANITY_ASSERT.
Referenced by Run(), RunPhaseFive(), RunPhaseFour(), and RunPhaseThree().
void scram::core::Preprocessor::RunPhaseThree () protected noexcept
Application of gate normalization.
After this phase, the graph is in normal form.
Note
Gate normalization is conducted.
Definition at line 358 of file preprocessor.cc.
References CheckRootGate(), scram::DEBUG3, LOG, NormalizeGates(), RunPhaseTwo(), and SANITY_ASSERT.
Referenced by Run().
void scram::core::Preprocessor::RunPhaseFour () protected noexcept
Propagation of complements.
Complements are propagated down to the variables in the graph. After this phase, the graph is in negation normal form.
Note
Complements are propagated to the variables of the graph.
Definition at line 372 of file preprocessor.cc.
References CheckRootGate(), scram::DEBUG3, scram::core::kAnd, scram::core::kNull, scram::core::kOr, LOG, PropagateComplements(), RunPhaseTwo(), and SANITY_ASSERT.
Referenced by scram::core::CustomPreprocessor< Zbdd >::Run().
void scram::core::Preprocessor::RunPhaseFive () protected noexcept
The final phase that cleans up the graph, and puts the structure of the graph ready for analysis.
This phase makes the graph structure alternating AND/OR gate layers.
Definition at line 397 of file preprocessor.cc.
References CheckRootGate(), CoalesceGates(), scram::DEBUG3, LOG, RunPhaseTwo(), and SANITY_ASSERT.
Referenced by scram::core::CustomPreprocessor< Zbdd >::Run().
bool scram::core::Preprocessor::CheckRootGate () protected noexcept
Checks the root gate of the graph for further processing.
The root gate may become constant or one-variable-NULL-gate, which signals the special case and no need for further processing.
Returns
true if no more processing is needed.
Postcondition
If no more processing is needed, the graph is fully ready for analysis.
Note
This function may swap the root gate of the graph.
Definition at line 475 of file preprocessor.cc.
References begin, scram::DEBUG3, scram::DEBUG4, scram::core::kNull, scram::core::kNullState, scram::core::kUnityState, and LOG.
Referenced by Run(), scram::core::CustomPreprocessor< Bdd >::Run(), scram::core::CustomPreprocessor< Zbdd >::Run(), scram::core::CustomPreprocessor< Mocus >::Run(), RunPhaseFive(), RunPhaseFour(), RunPhaseOne(), RunPhaseThree(), and RunPhaseTwo().
void scram::core::Preprocessor::RemoveNullGates () protected noexcept
Removes argument gates of NULL type, which means these arg gates have only one argument.
That one grand arg is transfered to the parent gate, and the original argument gate is removed from the parent gate.
This function is used only once to get rid of all NULL type gates at the very beginning of preprocessing.
Note
This function assumes that the container for NULL gates is empty. In other words, it is assumed no other function was trying to communicate NULL type gates for future processing.
This function is designed to be called only once at the start of preprocessing after cleaning all the constants from the graph.
Warning
There still may be only one NULL type gate which is the root of the graph. This must be handled separately.
NULL gates that are constant are not handled and left for constant propagation functions.
Definition at line 517 of file preprocessor.cc.
References ClearNullGates().
Referenced by RunPhaseOne().
void scram::core::Preprocessor::RemoveConstants () protected noexcept
Removes all Boolean constants from the Boolean graph according to the Boolean logic of the gates.
This function is only used to get rid of all constants registered by the Boolean graph at the very beginning of preprocessing.
Note
This is one of the first preprocessing steps. Other algorithms are safe to assume that there are no house events in the fault tree. Only possible constant nodes are gates that turn NULL or UNITY sets.
Warning
There still may be only one constant state gate which is the root of the graph. This must be handled separately.
Definition at line 526 of file preprocessor.cc.
References PropagateConstant().
Referenced by RunPhaseOne().
void scram::core::Preprocessor::PropagateConstant (const ConstantPtr & constant) protected noexcept
Propagates a Boolean constant bottom-up.
This is a helper function for initial cleanup of the Boolean graph.
Parameters
[in,out] constant The constant to be propagated.
Note
This function works together with NULL type and constant gate propagation functions to clean the results of the propagation.
Definition at line 540 of file preprocessor.cc.
References scram::core::kNull, and PropagateNullGate().
Referenced by ClearConstGates(), PropagateConstant(), PropagateNullGate(), and RemoveConstants().
void scram::core::Preprocessor::PropagateConstant (const GatePtr & gate) protected noexcept
Propagates constant gates bottom-up.
This is a helper function for algorithms that may produce and need to remove constant gates.
Parameters
[in,out] gate The gate that has become constant.
Note
This function works together with NULL type gate propagation function to cleanup the structure of the graph.
Warning
All parents of the gate will be removed, so the gate itself may get deleted unless it is the top gate.
Definition at line 552 of file preprocessor.cc.
References scram::core::kNull, scram::core::kUnityState, PropagateConstant(), and PropagateNullGate().
void scram::core::Preprocessor::PropagateNullGate (const GatePtr & gate) protected noexcept
Propagate NULL type gates bottom-up.
This is a helper function for algorithms that may produce and need to remove NULL type gates.
Parameters
[in,out] gate The gate that is NULL type.
Note
This function works together with constant state gate propagation function to cleanup the structure of the graph.
Warning
All parents of the gate will be removed, so the gate itself may get deleted unless it is the top gate.
Definition at line 566 of file preprocessor.cc.
References scram::core::kNull, and PropagateConstant().
Referenced by ClearNullGates(), and PropagateConstant().
void scram::core::Preprocessor::ClearConstGates () protected noexcept
Clears all constant gates registered for removal by algorithms or other preprocessing functions.
Warning
Gate marks will get cleared by this function.
Definition at line 580 of file preprocessor.cc.
References BLOG, scram::DEBUG5, and PropagateConstant().
Referenced by CoalesceGates(), MergeCommonArgs(), ProcessCommonNode(), and ProcessMultipleDefinitions().
void scram::core::Preprocessor::ClearNullGates () protected noexcept
Clears all NULL type gates registered for removal by algorithms or other preprocessing functions.
Warning
Gate marks will get cleared by this function.
Definition at line 591 of file preprocessor.cc.
References BLOG, scram::DEBUG5, and PropagateNullGate().
Referenced by DetectDistributivity(), MergeCommonArgs(), NormalizeGates(), ProcessCommonNode(), ProcessMultipleDefinitions(), and RemoveNullGates().
void scram::core::Preprocessor::NormalizeGates (bool full) protected noexcept
Normalizes the gates of the whole Boolean graph into OR, AND gates.
Parameters
[in] full A flag to handle complex gates like XOR and K/N, which generate a lot more new gates and make the structure of the graph more complex.
Note
The negation of the top gate is saved and handled as a special case for negation propagation because it does not have a parent.
New gates are created only upon full normalization of complex gates like XOR and K/N.
The full normalization is meant to be called only once.
Warning
The root get may still be NULL type.
Gate marks are used.
Node ordering may be used for full normalization.
Node visit information is used.
Definition at line 602 of file preprocessor.cc.
References AssignOrder(), ClearNullGates(), scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNot, scram::core::kNull, scram::core::kOr, scram::core::kVote, scram::core::kXor, NormalizeGate(), and NotifyParentsOfNegativeGates().
Referenced by RunPhaseOne(), and RunPhaseThree().
void scram::core::Preprocessor::NotifyParentsOfNegativeGates (const GatePtr & gate) protected noexcept
Notifies all parents of negative gates, such as NOT, NOR, and NAND, before transforming these gates into basic gates of OR and AND.
The argument gates are swapped with a negative sign.
Parameters
[in] gate The gate to start processing.
Note
This function is a helper function for NormalizeGates().
Warning
Gate marks must be clear.
This function does not change the types of gates.
The root gate does not have parents, so it is not handled here.
Definition at line 634 of file preprocessor.cc.
References scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNot, scram::core::kNull, scram::core::kOr, scram::core::kVote, and scram::core::kXor.
Referenced by NormalizeGates().
void scram::core::Preprocessor::NormalizeGate (const GatePtr & gate, bool full) protected noexcept
Normalizes complex gates into OR, AND gates.
Parameters
[in,out] gate The gate to be processed.
[in] full A flag to handle complex gates like XOR and K/N.
Note
This is a helper function for NormalizeGates().
This function registers NULL type gates for future removal.
Warning
Gate marks must be clear.
The parents of negative gates are assumed to be notified about the change of their arguments' types.
Definition at line 658 of file preprocessor.cc.
References scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNot, scram::core::kNull, scram::core::kOr, scram::core::kVote, scram::core::kXor, NormalizeVoteGate(), and NormalizeXorGate().
Referenced by NormalizeGates().
void scram::core::Preprocessor::NormalizeXorGate (const GatePtr & gate) protected noexcept
Normalizes a gate with XOR logic.
This is a helper function for the main gate normalization function.
Parameters
[in,out] gate The gate to normalize.
Note
This is a helper function for NormalizeGate.
Definition at line 701 of file preprocessor.cc.
References scram::core::kAnd, and scram::core::kOr.
Referenced by NormalizeGate().
void scram::core::Preprocessor::NormalizeVoteGate (const GatePtr & gate) protected noexcept
Normalizes a VOTE gate with a vote number.
The gate is turned into an OR gate of recursively normalized VOTE and AND arg gates according to the formula K/N(x, y_i) = OR(AND(x, K-1/N-1(y_i)), K/N-1(y_i))) with y_i being the rest of formula arguments, which exclude x. This representation is more friendly to other preprocessing and analysis techniques than the alternative, which is OR of AND gates of combinations. Normalization of K/N gates is aware of variable ordering.
Parameters
[in,out] gate The VOTE gate to normalize.
Precondition
Variable ordering is assigned to arguments.
This helper function is called from NormalizeGate.
Definition at line 724 of file preprocessor.cc.
References scram::core::kAnd, scram::core::kOr, and scram::core::kVote.
Referenced by NormalizeGate().
void scram::core::Preprocessor::PropagateComplements (const GatePtr & gate, bool keep_modules, std::unordered_map< int, GatePtr > * complements) protected noexcept
Propagates complements of argument gates down to leafs according to the De Morgan's law in order to remove any negative logic from the graph's gates.
The resulting graph will contain only positive gates, OR and AND types. After this function, the Boolean graph is in negation normal form.
Parameters
[in,out] gate The starting gate to traverse the graph. This is for recursive purposes.
[in] keep_modules A flag to NOT propagate complements to modules.
[in,out] complements The processed complements of shared gates.
Note
The graph must be normalized. It must contain only OR and AND gates.
Warning
Gate marks must be clear.
If the root gate has a negative sign, it must be handled before calling this function. The arguments and type of the gate must be inverted according to the logic of the root gate.
Definition at line 770 of file preprocessor.cc.
References scram::core::kAnd, and scram::core::kOr.
Referenced by RunPhaseFour().
bool scram::core::Preprocessor::CoalesceGates (bool common) protected noexcept
Runs gate coalescence on the whole Boolean graph.
Parameters
[in] common A flag to also coalesce common/shared gates. These gates may be important for other algorithms.
Returns
true if the graph has been changed.
Note
Module gates are omitted from coalescing to preserve them.
Warning
Gate marks are used.
Definition at line 823 of file preprocessor.cc.
References ClearConstGates().
Referenced by CoalesceGates(), RunPhaseFive(), and RunPhaseTwo().
bool scram::core::Preprocessor::CoalesceGates (const GatePtr & gate, bool common) protected noexcept
Coalesces positive argument gates with the same OR or AND logic as parents.
This function merges similar logic gates of NAND and NOR as well.
Parameters
[in,out] gate The starting gate to traverse the graph. This is for recursive purposes.
[in] common A flag to also join common gates. These gates may be important for other algorithms.
Returns
true if the given graph has been changed by this function.
false if no change has been made.
Note
Constant state gates may be generated upon joining. These gates are registered for future processing.
It is impossible that this function generates NULL type gates.
Module gates are omitted from coalescing to preserve them.
Warning
Gate marks are used.
Definition at line 836 of file preprocessor.cc.
References CoalesceGates(), scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNull, and scram::core::kOr.
bool scram::core::Preprocessor::ProcessMultipleDefinitions () protected noexcept
Detects and replaces multiple definitions of gates.
Gates with the same logic and inputs but different indices are considered redundant.
Returns
true if multiple definitions are found and replaced.
Note
This function does not recursively detect multiple definitions due to replaced redundant arguments of gates. The replaced gates are considered a new graph, and this function must be called again to verify that the new graph does not have multiple definitions.
Definition at line 889 of file preprocessor.cc.
References ClearConstGates(), ClearNullGates(), scram::DEBUG4, scram::DEBUG5, DetectMultipleDefinitions(), LOG, and ReplaceGate().
Referenced by RunPhaseTwo().
void scram::core::Preprocessor::DetectMultipleDefinitions (const GatePtr & gate, std::unordered_map< GatePtr, std::vector< GateWeakPtr >> * multi_def, GateSet * unique_gates) protected noexcept
Traverses the Boolean graph to collect multiple definitions of gates.
Parameters
[in] gate The gate to traverse the sub-graph.
[in,out] multi_def Detected multiple definitions.
[in,out] unique_gates A set of semantically unique gates.
Warning
Gate marks must be clear.
Definition at line 921 of file preprocessor.cc.
Referenced by ProcessMultipleDefinitions().
void scram::core::Preprocessor::DetectModules () protected noexcept
Traverses the Boolean graph to detect modules.
Modules are independent sub-graphs without common nodes with the rest of the graph.
Definition at line 944 of file preprocessor.cc.
References AssignTiming(), scram::DEBUG4, FindModules(), and LOG.
Referenced by RunPhaseTwo().
int scram::core::Preprocessor::AssignTiming (int time, const GatePtr & gate) protected noexcept
Traverses the given gate and assigns time of visit to nodes.
Parameters
[in] time The current time.
[in,out] gate The gate to traverse and assign time to.
Returns
The final time of traversing.
Definition at line 963 of file preprocessor.cc.
Referenced by DecomposeCommonNodes(), and DetectModules().
void scram::core::Preprocessor::FindModules (const GatePtr & gate) protected noexcept
Determines modules from original gates that have been already timed.
This function can also create new modules from the existing graph.
Parameters
[in,out] gate The gate to test for modularity.
Definition at line 980 of file preprocessor.cc.
References scram::DEBUG4, LOG, and ProcessModularArgs().
Referenced by DetectModules().
void scram::core::Preprocessor::ProcessModularArgs (const GatePtr & gate, const std::vector< std::pair< int, NodePtr >> & non_shared_args, std::vector< std::pair< int, NodePtr >> * modular_args, std::vector< std::pair< int, NodePtr >> * non_modular_args) protected noexcept
Processes gate arguments found during the module detection.
Parameters
[in,out] gate The gate with the arguments.
[in] non_shared_args Args that belong only to this gate.
[in,out] modular_args Args that may be grouped into new modules.
[in,out] non_modular_args Args that cannot be grouped into modules.
Definition at line 1045 of file preprocessor.cc.
References CreateNewModule(), CreateNewModules(), FilterModularArgs(), GroupModularArgs(), scram::core::kAnd, scram::core::kNand, scram::core::kNor, and scram::core::kOr.
Referenced by FindModules().
GatePtr scram::core::Preprocessor::CreateNewModule (const GatePtr & gate, const std::vector< std::pair< int, NodePtr >> & args) protected noexcept
Creates a new module as an argument of an existing gate if the logic of the existing parent gate allows a sub-module.
The existing arguments of the original gate are used to create the new module. If the new module must contain all the arguments, the original gate is asserted to be a module, and no operation is performed.
Parameters
[in,out] gate The parent gate for a module.
[in] args Modular arguments to be added into the new module.
Returns
Pointer to the new module if it is created.
Definition at line 1074 of file preprocessor.cc.
References scram::DEBUG4, scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kOr, and LOG.
Referenced by CreateNewModules(), and ProcessModularArgs().
void scram::core::Preprocessor::FilterModularArgs (std::vector< std::pair< int, NodePtr >> * modular_args, std::vector< std::pair< int, NodePtr >> * non_modular_args) protected noexcept
Checks if a group of modular arguments share anything with non-modular arguments.
If so, then the modular arguments are not actually modular, and those arguments are removed from modular containers. This is due to chain of nodes that are shared between modular and non-modular arguments.
Parameters
[in,out] modular_args Candidates for modular grouping.
[in,out] non_modular_args Non modular arguments.
Definition at line 1112 of file preprocessor.cc.
Referenced by ProcessModularArgs().
void scram::core::Preprocessor::GroupModularArgs (std::vector< std::pair< int, NodePtr >> * modular_args, std::vector< std::vector< std::pair< int, NodePtr >>> * groups) protected noexcept
Groups modular arguments by their common elements.
The gates created with these modular arguments are guaranteed to be independent modules.
Parameters
[in,out] modular_args Candidates for modular grouping.
[out] groups Grouped modular arguments.
Definition at line 1141 of file preprocessor.cc.
References scram::DEBUG4, and LOG.
Referenced by ProcessModularArgs().
void scram::core::Preprocessor::CreateNewModules (const GatePtr & gate, const std::vector< std::pair< int, NodePtr >> & modular_args, const std::vector< std::vector< std::pair< int, NodePtr >>> & groups) protected noexcept
Creates new module gates from groups of modular arguments if the logic of the parent gate allows sub-modules.
The existing arguments of the original gate are used to create the new modules. If all the parent gate arguments are modular and within one group, the parent gate is asserted to be a module gate, and no operation is performed.
Parameters
[in,out] gate The parent gate for a module.
[in] modular_args All the modular arguments.
[in] groups Grouped modular arguments.
Definition at line 1186 of file preprocessor.cc.
References CreateNewModule().
Referenced by ProcessModularArgs().
std::vector< GateWeakPtr > scram::core::Preprocessor::GatherModules () protected noexcept
Gathers all modules in the Boolean graph.
Returns
Unique modules encountered breadth-first.
Precondition
Module detection and marking has already been performed.
Warning
Gate marks are used.
Definition at line 1213 of file preprocessor.cc.
References scram::core::Gate::args(), and scram::core::Gate::mark().
Referenced by MergeCommonArgs().
bool scram::core::Preprocessor::MergeCommonArgs () protected noexcept
Identifies common arguments of gates, and merges the common arguments into new gates.
This technique helps uncover the common structure within gates that are not modules.
Returns
true if the graph structure is changed by this technique.
Note
This technique works only with OR/AND gates. Partial or full normalization may make this technique more effective.
Constant arguments are not expected.
Warning
Gate marks are used for traversal.
Node counts are used for common node detection.
Definition at line 1241 of file preprocessor.cc.
References scram::DEBUG4, scram::core::kAnd, scram::core::kOr, and LOG.
Referenced by RunPhaseTwo().
bool scram::core::Preprocessor::MergeCommonArgs (Operator op) protected noexcept
Merges common arguments for a specific group of gates.
The gates are grouped by their operators. This is a helper function that divides the main merging technique by the gate types.
Parameters
[in] op The operator that defines the group.
Returns
true if common args are merged into gates.
Note
The operator or logic of the gates must allow merging. OR/AND operators are expected.
Warning
Gate marks are used for traversal.
Node counts are used for common node detection.
Definition at line 1259 of file preprocessor.cc.
References ClearConstGates(), ClearNullGates(), scram::DEBUG4, FilterMergeCandidates(), GatherCommonArgs(), GatherModules(), GroupCandidatesByArgs(), GroupCommonArgs(), GroupCommonParents(), scram::core::Preprocessor::MergeTable::groups, scram::core::kAnd, scram::core::kOr, LOG, MarkCommonArgs(), op, and TransformCommonArgs().
void scram::core::Preprocessor::MarkCommonArgs (const GatePtr & gate, Operator op) protected noexcept
Marks common arguments of gates with a specific operator.
Parameters
[in] gate The gate to start the traversal.
[in] op The operator of gates which arguments must be marked.
Note
Node count information is used to mark the common arguments.
Warning
Gate marks are used for linear traversal.
Definition at line 1307 of file preprocessor.cc.
References op.
Referenced by MergeCommonArgs().
void scram::core::Preprocessor::GatherCommonArgs (const GatePtr & gate, Operator op, MergeTable::Candidates * group) protected noexcept
Gathers common arguments of the gates in the group of a specific operator.
The common arguments must be marked by the second visit exit time.
Parameters
[in] gate The gate to start the traversal.
[in] op The operator of gates in the group.
[out] group The group of the gates with their common arguments.
Note
The common arguments are sorted.
The gathering is limited by modules. That is, no search is performed in submodules because they don't have common args with the supermodule.
Warning
Gate marks are used for linear traversal.
Definition at line 1331 of file preprocessor.cc.
References op.
Referenced by MergeCommonArgs().
void scram::core::Preprocessor::FilterMergeCandidates (MergeTable::Candidates * candidates) protected noexcept
Filters merge candidates and their shared arguments to detect opportunities for simplifications like gate substitutions.
Parameters
[in,out] candidates The group of merge candidate gates
Note
The simplifications are based on optimistic heuristics, and the end result may not be the most optimal.
Warning
May produce NULL type and constant gates.
Todo:
Consider repeating until no change can be made.
Definition at line 1370 of file preprocessor.cc.
References end, and scram::core::kNull.
Referenced by MergeCommonArgs().
void scram::core::Preprocessor::GroupCandidatesByArgs (MergeTable::Candidates * candidates, std::vector< MergeTable::Candidates > * groups) protected noexcept
Groups candidates with common arguments.
The groups do not intersect either by candidates or common arguments.
Parameters
[in,out] candidates The group of the gates with their common args.
[out] groups Non-intersecting collection of groups of candidates.
Note
Groups with only one member are discarded.
Definition at line 1429 of file preprocessor.cc.
References BLOG, and scram::DEBUG4.
Referenced by MergeCommonArgs().
void scram::core::Preprocessor::GroupCommonParents (int num_common_args, const MergeTable::Candidates & group, MergeTable::Collection * parents) protected noexcept
Finds intersections of common arguments of gates.
Gates with the same common arguments are grouped to represent common parents for the arguments.
Parameters
[in] num_common_args The least number common arguments to consider.
[in] group The group of the gates with their common arguments.
[out] parents Grouped common parent gates for the sets of common arguments.
Note
The common arguments are sorted.
Definition at line 1496 of file preprocessor.cc.
Referenced by HandleDistributiveArgs(), and MergeCommonArgs().
void scram::core::Preprocessor::GroupCommonArgs (const MergeTable::Collection & options, MergeTable * table) protected noexcept
Groups common args for merging.
The common parents of arguments are isolated into groups so that other groups are not affected by the merging operations.
Parameters
[in] options Combinations of common args and distributive gates.
[out] table Groups of distributive gates for separate manipulation.
Todo:
This strategy deletes too many groups. The intersections must be considered for each option.
Definition at line 1519 of file preprocessor.cc.
References FindOptionGroup(), and gates.
Referenced by MergeCommonArgs().
void scram::core::Preprocessor::FindOptionGroup (MergeTable::MergeGroup * all_options, MergeTable::OptionGroup * best_group) protected noexcept
Finds an optimal way of grouping options.
The goal of this function is to maximize the effect of gate merging or common argument factorization.
After common arguments and parents are grouped, the merging technique must find the most optimal strategy to create new gates that will represent the common arguments. The strategy may favor modularity, size, or other parameters of the new structure of the final graph. The common elements within the groups of common parents and common arguments create the biggest challenge for finding the optimal solution. For example, { (a, b) : (p1, p2), (b, c) : (p2, p3) } The strategy has to make the most optimal choice between two mutually exclusive options.
Parameters
[in] all_options The sorted set of options. The options must be sorted in ascending size of common arguments.
[out] best_group The optimal group of options.
Note
The all_options parameter is not passed by const reference because the best group must store non const pointers to options. It is expected that the chosen options will be manipulated by the user of this function through these pointers. However, this function guarantees not to manipulate or change the set of all options.
Todo:
The current logic misses opportunities that may branch with the same base option.
Definition at line 1556 of file preprocessor.cc.
References FindBaseOption().
Referenced by GroupCommonArgs(), and GroupDistributiveArgs().
void scram::core::Preprocessor::FindBaseOption (MergeTable::MergeGroup * all_options, MergeTable::MergeGroup::iterator * best_option) protected noexcept
Finds the starting option for group formation.
Parameters
[in] all_options The sorted set of options. The options must be sorted in ascending size of common arguments.
[out] best_option The optimal starting option if any. If not found, iterator at the end of the group.
Definition at line 1589 of file preprocessor.cc.
Referenced by FindOptionGroup().
void scram::core::Preprocessor::TransformCommonArgs (MergeTable::MergeGroup * group) protected noexcept
Transforms common arguments of gates into new gates.
Parameters
[in,out] group Group of merge options for manipulation.
Definition at line 1622 of file preprocessor.cc.
References scram::DEBUG5, scram::core::kNull, and LOG.
Referenced by MergeCommonArgs().
bool scram::core::Preprocessor::DetectDistributivity () protected noexcept
Detects and manipulates AND and OR gate distributivity for the whole graph.
Returns
true if the graph is changed.
Definition at line 1666 of file preprocessor.cc.
References ClearNullGates().
Referenced by DetectDistributivity(), and RunPhaseTwo().
bool scram::core::Preprocessor::DetectDistributivity (const GatePtr & gate) protected noexcept
Detects and manipulates AND and OR gate distributivity.
For example, (a | b) & (a | c) = a | b & c.
Parameters
[in] gate The gate which arguments and subgraph must be tested.
Returns
true if transformations are performed.
Note
This algorithm does not produce constant gates.
NULL type gates are registered if produced.
Warning
Gate marks must be clear.
Definition at line 1676 of file preprocessor.cc.
References DetectDistributivity(), HandleDistributiveArgs(), scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNull, and scram::core::kOr.
bool scram::core::Preprocessor::HandleDistributiveArgs (const GatePtr & gate, Operator distr_type, std::vector< GatePtr > * candidates) protected noexcept
Manipulates gates with distributive arguments.
Designed to work with distributivity detection and manipulation logic.
Parameters
[in,out] gate The gate which arguments must be manipulated.
[in] distr_type The type of distributive arguments.
[in,out] candidates Candidates for distributivity check.
Returns
true if transformations are performed.
Definition at line 1714 of file preprocessor.cc.
References scram::DEBUG4, scram::DEBUG5, FilterDistributiveArgs(), gates, GroupCommonParents(), GroupDistributiveArgs(), scram::core::Preprocessor::MergeTable::groups, scram::core::kAnd, scram::core::kOr, LOG, and TransformDistributiveArgs().
Referenced by DetectDistributivity().
bool scram::core::Preprocessor::FilterDistributiveArgs (const GatePtr & gate, std::vector< GatePtr > * candidates) protected noexcept
Detects relationships between the gate and its distributive arguments to remove unnecessary candidates.
The determination of redundant candidates follow the Boolean logic. For example, if any argument is superset of another argument, it can be removed from the gate.
Parameters
[in,out] gate The gate which arguments must be filtered.
[in,out] candidates Candidates for distributivity check.
Returns
true if the candidates and the gate are manipulated.
Note
The redundant candidates are also removed from the gate.
Definition at line 1775 of file preprocessor.cc.
References scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNot, scram::core::kNull, and scram::core::kOr.
Referenced by HandleDistributiveArgs().
void scram::core::Preprocessor::GroupDistributiveArgs (const MergeTable::Collection & options, MergeTable * table) protected noexcept
Groups distributive gate arguments for future factorization.
The function tries to maximize the return from the gate manipulations.
Parameters
[in] options Combinations of common args and distributive gates.
[out] table Groups of distributive gates for separate manipulation.
Todo:
Evaluate various grouping strategies as in common arg merging.
Definition at line 1832 of file preprocessor.cc.
References FindOptionGroup(), and gates.
Referenced by HandleDistributiveArgs().
void scram::core::Preprocessor::TransformDistributiveArgs (const GatePtr & gate, Operator distr_type, MergeTable::MergeGroup * group) protected noexcept
Transforms distributive of arguments gates into a new subgraph.
Parameters
[in,out] gate The parent gate of all the distributive arguments.
[in] distr_type The type of distributive arguments.
[in,out] group Group of distributive args options for manipulation.
Definition at line 1863 of file preprocessor.cc.
References gates, scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNull, and scram::core::kOr.
Referenced by HandleDistributiveArgs().
void scram::core::Preprocessor::BooleanOptimization () protected noexcept
Propagates failures of common nodes to detect redundancy.
The graph structure is optimized by removing the redundancies if possible. This optimization helps reduce the number of common nodes.
Warning
Boolean optimization may replace the root gate of the graph.
Node visit information is manipulated.
Gate marks are manipulated.
Node optimization values are manipulated.
Definition at line 1932 of file preprocessor.cc.
References GatherCommonNodes(), and ProcessCommonNode().
Referenced by RunPhaseTwo().
void scram::core::Preprocessor::GatherCommonNodes (std::vector< GateWeakPtr > * common_gates, std::vector< std::weak_ptr< Variable >> * common_variables) protected noexcept
Traverses the graph to find nodes that have more than one parent.
Common nodes are encountered breadth-first, and they are unique.
Parameters
[out] common_gates Gates with more than one parent.
[out] common_variables Common variables.
Note
Constant nodes are not expected to be operated.
Warning
Node visit information is manipulated.
Definition at line 1950 of file preprocessor.cc.
References scram::core::Gate::args(), and scram::core::Node::Visit().
Referenced by BooleanOptimization(), and DecomposeCommonNodes().
template<class N > void scram::core::Preprocessor::ProcessCommonNode (const std::weak_ptr< N > & common_node) protected noexcept
Tries to simplify the graph by removing redundancies generated by a common node.
Template Parameters
N Non-Node, concrete (i.e. Gate, etc.) type.
Parameters
[in] common_node A node with more than one parent.
Definition at line 1981 of file preprocessor.cc.
References ClearConstGates(), ClearNullGates(), ClearStateMarks(), CollectRedundantParents(), CollectStateDestinations(), scram::DEBUG4, LOG, MarkAncestors(), ProcessRedundantParents(), ProcessStateDestinations(), and PropagateState().
Referenced by BooleanOptimization().
void scram::core::Preprocessor::MarkAncestors (const NodePtr & node, GatePtr * module) protected noexcept
Marks ancestor gates true.
The marking stops at the root of an independent subgraph for algorithmic efficiency.
Parameters
[in] node The child node.
[out] module The root module gate ancestor.
Precondition
Gate marks are clear.
Warning
Since very specific branches are marked 'true', cleanup must be performed after/with the use of the ancestors. If the cleanup is done improperly or not at all, the default global contract of clean marks will be broken.
Definition at line 2034 of file preprocessor.cc.
Referenced by ProcessCommonNode().
int scram::core::Preprocessor::PropagateState (const GatePtr & gate, const NodePtr & node) protected noexcept
Propagates failure or success of a common node by setting its ancestors' optimization values to 1 or -1 if they fail or succeed according to their Boolean logic.
The failure of an argument is similar to propagating constant TRUE/1. The success of an argument is similar to propagating constant FALSE/-1.
Parameters
[in,out] gate The root gate under consideration.
[in] node The node that is the source of failure.
Returns
Total multiplicity of the node.
Precondition
The optimization value of the main common node is 1 or -1.
The marks of ancestor gates are 'true'.
Postcondition
The marks of all ancestor gates are reset to 'false'.
All ancestor gates are marked with the descendant index.
Definition at line 2051 of file preprocessor.cc.
References DetermineGateState(), and scram::core::Node::opti_value().
Referenced by ProcessCommonNode().
void scram::core::Preprocessor::DetermineGateState (const GatePtr & gate, int num_failure, int num_success) protected noexcept
Determines if a gate fails or succeeds due to failed/succeeded arguments.
If gates fails, its optimization value is set to 1. If it succeeds, its optimization value is -1. If the state is indeterminate, the optimization value is 0.
Parameters
[in,out] gate The gate with the arguments.
[in] num_failure The number of failure (TRUE/1) arguments.
[in] num_success The number of success (FALSE/-1) arguments.
Definition at line 2093 of file preprocessor.cc.
References scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNot, scram::core::kNull, scram::core::kOr, scram::core::kVote, and scram::core::kXor.
Referenced by PropagateState().
int scram::core::Preprocessor::CollectStateDestinations (const GatePtr & gate, int index, std::unordered_map< int, GateWeakPtr > * destinations) protected noexcept
Collects failure or success destinations and marks non-redundant nodes.
The optimization value for non-redundant gates are set to 2.
Parameters
[in] gate The non-failed gate which sub-graph is to be traversed.
[in] index The index of the main state-source common node.
[in,out] destinations Destinations of the state.
Returns
The number of encounters with the destinations.
Definition at line 2147 of file preprocessor.cc.
Referenced by ProcessCommonNode().
void scram::core::Preprocessor::CollectRedundantParents (const NodePtr & node, std::unordered_map< int, GateWeakPtr > * destinations, std::vector< GateWeakPtr > * redundant_parents) protected noexcept
Detects if parents of a node are redundant.
Parameters
[in] node The common node.
[in,out] destinations Destinations of the state.
[out] redundant_parents A set of redundant parents.
Precondition
Destinations have valid state (Success or Failure).
Non-redundant parents have optimization value 2.
Postcondition
Destinations that are also redundant parents are removed if the semantics of the transformations is equivalent.
Definition at line 2173 of file preprocessor.cc.
References scram::core::kAnd, and scram::core::kOr.
Referenced by ProcessCommonNode().
void scram::core::Preprocessor::ProcessRedundantParents (const NodePtr & node, const std::vector< GateWeakPtr > & redundant_parents) protected noexcept
Detects if parents of a node are redundant.
If there are redundant parents, depending on the logic of the parent, the node is removed from the parent unless it is also in the destination set with specific logic. In the latter case, the parent is removed from the destinations.
Parameters
[in] node The common node.
[in] redundant_parents A set of redundant parents.
Note
Constant gates are registered for removal.
Null type gates are registered for removal.
Definition at line 2199 of file preprocessor.cc.
References scram::core::kNull.
Referenced by ProcessCommonNode().
template<class N > void scram::core::Preprocessor::ProcessStateDestinations (const std::shared_ptr< N > & node, const std::unordered_map< int, GateWeakPtr > & destinations) protected noexcept
Transforms failure or success destination according to the logic and the common node.
Template Parameters
N Non-Node, concrete (i.e. Gate, etc.) type.
Parameters
[in] node The common node.
[in] destinations Destination gates for the state.
Warning
This function will replace the root gate of the graph if it is the destination.
Definition at line 2217 of file preprocessor.cc.
References scram::core::kAnd, scram::core::kNull, scram::core::kOr, and ReplaceGate().
Referenced by ProcessCommonNode().
void scram::core::Preprocessor::ClearStateMarks (const GatePtr & gate) protected noexcept
Clears all the ancestor marks used in Boolean optimization steps.
Parameters
[in] gate The top ancestor of the common node.
Precondition
All ancestor gates are marked with the descendant index.
The common node itself is not the ancestor.
Warning
The common node must be cleaned separately.
Definition at line 2252 of file preprocessor.cc.
Referenced by ProcessCommonNode().
bool scram::core::Preprocessor::DecomposeCommonNodes () protected noexcept
The Shannon decomposition for common nodes in the Boolean graph.
This procedure is also called "Constant Propagation", but it is confusing with the actual propagation of house events and constant gates.
The main two operations are performed according to the Shannon decomposition of particular setups:
x & f(x, y) = x & f(1, y) x | f(x, y) = x | f(0, y)
Returns
true if the setups are found and processed.
Note
This preprocessing algorithm may introduce clones of existing shared gates, which may increase the size of the graph and complicate application and performance of other algorithms.
Warning
Gate descendant marks are used.
Gate ancestor marks are used.
Node visit information is used.
Gate marks are used.
Definition at line 2265 of file preprocessor.cc.
References AssignTiming(), and GatherCommonNodes().
Referenced by RunPhaseTwo().
void scram::core::Preprocessor::MarkCoherence () protected noexcept
Marks coherence of the whole graph.
Warning
Gate marks are used.
Definition at line 2502 of file preprocessor.cc.
Referenced by MarkCoherence(), scram::core::CustomPreprocessor< Bdd >::Run(), and scram::core::CustomPreprocessor< Zbdd >::Run().
void scram::core::Preprocessor::MarkCoherence (const GatePtr & gate) protected noexcept
Marks gates with coherence flags.
Parameters
[in] gate The root gate for processing.
Warning
Gate marks are used.
Definition at line 2509 of file preprocessor.cc.
References scram::core::kNand, scram::core::kNor, scram::core::kNot, scram::core::kXor, and MarkCoherence().
void scram::core::Preprocessor::ReplaceGate (const GatePtr & gate, const GatePtr & replacement) protected noexcept
Replaces one gate in the graph with another.
Parameters
[in,out] gate An existing gate to be replaced.
[in,out] replacement A gate that will replace the old gate.
Postcondition
The sign of the existing gate as an argument is transfered to the replacement gate.
If any parent becomes constant or NULL type, the parent is registered for removal.
Definition at line 2541 of file preprocessor.cc.
References scram::core::kNull.
Referenced by ProcessMultipleDefinitions(), and ProcessStateDestinations().
bool scram::core::Preprocessor::RegisterToClear (const GatePtr & gate) protected noexcept
Registers mutated gates for potential deletion later.
Parameters
[in] gate The mutated gate under examination.
Returns
true if the gate is registered for clearance.
Precondition
The caller will later call the appropriate cleanup functions.
Definition at line 2558 of file preprocessor.cc.
References scram::core::kNull.
void scram::core::Preprocessor::AssignOrder () protected noexcept
Assigns order for Boolean graph variables.
Precondition
Old node order marks are allowed to get cleaned.
Postcondition
Node order marks contain the ordering.
Definition at line 2570 of file preprocessor.cc.
References TopologicalOrder().
Referenced by NormalizeGates(), scram::core::CustomPreprocessor< Bdd >::Run(), and scram::core::CustomPreprocessor< Zbdd >::Run().
int scram::core::Preprocessor::TopologicalOrder (Gate * root, int order) protected noexcept
Assigns topological ordering to nodes of the Boolean Graph.
The ordering is assigned to the node order marks. The nodes are sorted in descending optimization value. The highest order value belongs to the root.
Parameters
[in,out] root The root or current parent gate of the graph.
[in] order The current order value.
Returns
The final order value.
Postcondition
The root and descendant node order marks contain the ordering.
Definition at line 2575 of file preprocessor.cc.
Referenced by AssignOrder().
template<class T > std::vector< T * > scram::core::Preprocessor::OrderArguments (const Gate & gate) protected noexcept
Determines the order of traversal for gate arguments.
This function does assign the order of nodes.
Template Parameters
T Type of the arguments.
Parameters
[in] gate The host gate parent.
Returns
An ordered, stable list of arguments.
Definition at line 2591 of file preprocessor.cc.
void scram::core::Preprocessor::GatherNodes (std::vector< GatePtr > * gates, std::vector< VariablePtr > * variables) protected noexcept
Gathers all nodes in the Boolean graph.
Parameters
[out] gates A set of gates.
[out] variables A set of variables.
Warning
Node visit information is manipulated.
Definition at line 2602 of file preprocessor.cc.
References gates, and variables.
Referenced by GatherNodes(), and scram::core::CustomPreprocessor< Mocus >::Run().
void scram::core::Preprocessor::GatherNodes (const GatePtr & gate, std::vector< GatePtr > * gates, std::vector< VariablePtr > * variables) protected noexcept
Gathers nodes in the sub-graph.
Parameters
[in] gate The root gate to traverse.
[in,out] gates A set of gates.
[in,out] variables A set of variables.
Precondition
Visited nodes are marked.
Definition at line 2608 of file preprocessor.cc.
References gates, GatherNodes(), and variables.
const BooleanGraph& scram::core::Preprocessor::graph () const inline protected
Returns
The graph under processing.
Definition at line 1102 of file preprocessor.h.
Referenced by scram::core::CustomPreprocessor< Zbdd >::Run().
The documentation for this class was generated from the following files:
preprocessor.h
preprocessor.cc