scram::core::BooleanGraph Class Reference
scram::core::BooleanGraph Class Reference
BooleanGraph is a propositional directed acyclic graph (PDAG).
#include <boolean_graph.h>
Public Member Functions
BooleanGraph (const mef::Gate &root, bool ccf=false) noexcept
Constructs a BooleanGraph starting from the top gate of a fault tree.
bool coherent () const
bool normal () const
const GatePtr & root () const
bool complement () const
const std::vector< mef::BasicEvent * > & basic_events () const
mef::BasicEvent * GetBasicEvent (int index) const
Helper function to map the results of the indexation to the original basic events.
void Print ()
Prints the Boolean graph in the Aralia format.
void Log () noexcept
Writes Boolean graph properties into logs.
Friends
class Preprocessor
The main manipulator of Boolean graphs.
Detailed Description
BooleanGraph is a propositional directed acyclic graph (PDAG).
Todo:
This can be decoupled.
This class provides a simpler representation of a fault tree that takes into account the indices of events instead of IDs and pointers. This graph can also be called an indexed fault tree.
This class is designed to help preprocessing and other graph transformation functions.
Warning
Never hold a shared pointer to any other indexed gate except for the root gate of a Boolean graph. Extra reference count will prevent automatic deletion of the node and management of the structure of the graph. Moreover, the graph may become a multiple-top-event fault tree, which is not the assumption of all the other preprocessing and analysis algorithms.
Definition at line 780 of file boolean_graph.h.
Constructor & Destructor Documentation
scram::core::BooleanGraph::BooleanGraph (const mef::Gate & root, bool ccf = false) explicit noexcept
Constructs a BooleanGraph starting from the top gate of a fault tree.
Upon construction, features of the fault tree are recorded to help preprocessing and analysis functions.
Parameters
[in] root The top gate of the fault tree.
[in] ccf Incorporation of CCF gates and events for CCF groups.
Postcondition
The BooleanGraph is stable as long as the argument fault tree and its underlying containers are stable. If the fault tree has been manipulated (event addition, etc.), its BooleanGraph representation is not guaranteed to be the same.
Definition at line 444 of file boolean_graph.cc.
References scram::core::Node::ResetIndex(), and scram::core::Variable::ResetIndex().
Member Function Documentation
bool scram::core::BooleanGraph::coherent () const inline
Returns
true if the fault tree is coherent.
Definition at line 800 of file boolean_graph.h.
bool scram::core::BooleanGraph::normal () const inline
Returns
true if all gates of the fault tree are normalized AND/OR.
Definition at line 803 of file boolean_graph.h.
Referenced by scram::core::Preprocessor::Run().
const GatePtr& scram::core::BooleanGraph::root () const inline
Returns
The current root gate of the graph.
Definition at line 806 of file boolean_graph.h.
Referenced by scram::core::Mocus::Analyze(), scram::core::Bdd::Bdd(), scram::core::Mocus::Mocus(), and scram::core::operator<<().
bool scram::core::BooleanGraph::complement () const inline
Returns
true if the root must be complemented.
Definition at line 809 of file boolean_graph.h.
Referenced by scram::core::Bdd::Bdd().
const std::vector<mef::BasicEvent*>& scram::core::BooleanGraph::basic_events () const inline
Returns
Original basic event as initialized in this indexed fault tree. The position of a basic event equals (its index - 1).
Definition at line 814 of file boolean_graph.h.
Referenced by scram::core::Mocus::products().
mef::BasicEvent* scram::core::BooleanGraph::GetBasicEvent (int index) const inline
Helper function to map the results of the indexation to the original basic events.
This function, for example, helps transform products with indices into products with IDs or pointers.
Parameters
[in] index Positive index of the basic event.
Returns
Pointer to the original basic event from its index.
Definition at line 827 of file boolean_graph.h.
References constants, gates, scram::core::operator<<(), scram::core::Print(), and variables.
Referenced by scram::core::ImportanceAnalysis::GatherImportantEvents().
void scram::core::BooleanGraph::Print ()
Prints the Boolean graph in the Aralia format.
This is a helper for logging and debugging. The output is the standard error.
Warning
Node visits are used.
Definition at line 454 of file boolean_graph.cc.
void scram::core::BooleanGraph::Log () noexcept
Writes Boolean graph properties into logs.
Precondition
The graph is valid and well formed.
Logging cutoff level is Debug 4 or higher.
Postcondition
Gate marks are clear.
Warning
Gate marks are manipulated.
Definition at line 781 of file boolean_graph.cc.
References BLOG, scram::DEBUG4, scram::DEBUG5, scram::core::kAnd, scram::core::kNand, scram::core::kNor, scram::core::kNot, scram::core::kNull, scram::core::kOr, scram::core::kVote, scram::core::kXor, LOG, and scram::Logger::report_level().
The documentation for this class was generated from the following files:
boolean_graph.h
boolean_graph.cc