scram::mef::Expression Class Reference
scram::mef::Expression Class Reference abstract
Abstract base class for all sorts of expressions to describe events.
#include <expression.h>
Classes
class Cycle
Provides access to cycle-destructive functions.
Public Member Functions
Expression (std::vector< ExpressionPtr > args)
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
virtual void Validate () const
Validates the expression.
virtual double Mean () noexcept=0
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual bool IsConstant () noexcept
Determines if the value of the expression varies.
virtual double Max () noexcept
virtual double Min () noexcept
Protected Member Functions
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
Abstract base class for all sorts of expressions to describe events.
This class also acts like a connector for parameter nodes and may create cycles. Expressions are not expected to be shared except for parameters. In addition, expressions are not expected to be changed after validation phases.
Definition at line 49 of file expression.h.
Constructor & Destructor Documentation
scram::mef::Expression::Expression (std::vector< ExpressionPtr > args) explicit
Constructor for use by derived classes to register their arguments.
Parameters
[in] args Arguments of this expression.
Definition at line 28 of file expression.cc.
Member Function Documentation
const std::vector<ExpressionPtr>& scram::mef::Expression::args () const inline
Returns
A set of arguments of the expression.
Definition at line 79 of file expression.h.
Referenced by scram::mef::BinaryExpression::BinaryExpression(), scram::mef::cycle::GetConnectors(), scram::mef::cycle::GetNodes(), scram::mef::Histogram::Histogram(), scram::mef::Mul::Mean(), scram::mef::Div::Mean(), scram::mef::Add::Min(), scram::mef::Sub::Min(), and scram::mef::Div::Validate().
virtual void scram::mef::Expression::Validate () const inline virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
InvalidArgument The arguments are invalid for setup.
Reimplemented in scram::mef::Histogram, scram::mef::BetaDeviate, scram::mef::Div, scram::mef::GammaDeviate, scram::mef::WeibullExpression, scram::mef::LogNormalDeviate, scram::mef::GlmExpression, scram::mef::NormalDeviate, scram::mef::UniformDeviate, and scram::mef::ExponentialExpression.
Definition at line 85 of file expression.h.
References IsConstant(), Mean(), Reset(), and Sample().
virtual double scram::mef::Expression::Mean () pure virtual noexcept
Returns
The mean value of this expression.
Implemented in scram::mef::Histogram, scram::mef::BetaDeviate, scram::mef::Div, scram::mef::GammaDeviate, scram::mef::Mul, scram::mef::WeibullExpression, scram::mef::LogNormalDeviate, scram::mef::Sub, scram::mef::GlmExpression, scram::mef::NormalDeviate, scram::mef::Parameter, scram::mef::Add, scram::mef::UniformDeviate, scram::mef::ConstantExpression, scram::mef::ExponentialExpression, and scram::mef::Neg.
Referenced by Max(), scram::mef::LogNormalDeviate::Max(), scram::mef::Neg::Mean(), scram::mef::ExponentialExpression::Mean(), scram::mef::Add::Mean(), scram::mef::Parameter::Mean(), scram::mef::GlmExpression::Mean(), scram::mef::Sub::Mean(), Min(), scram::mef::ExponentialExpression::Validate(), scram::mef::UniformDeviate::Validate(), scram::mef::NormalDeviate::Validate(), scram::mef::GlmExpression::Validate(), Validate(), scram::mef::LogNormalDeviate::Validate(), scram::mef::WeibullExpression::Validate(), scram::mef::GammaDeviate::Validate(), scram::mef::BetaDeviate::Validate(), and scram::mef::Histogram::Validate().
double scram::mef::Expression::Sample () noexcept
Returns
A sampled value of this expression.
Definition at line 33 of file expression.cc.
Referenced by scram::mef::GammaDeviate::Max(), scram::mef::BetaDeviate::Max(), scram::mef::GlmExpression::Mean(), scram::mef::Neg::Min(), scram::mef::ExponentialExpression::Min(), scram::mef::Add::Min(), scram::mef::Parameter::Min(), scram::mef::Sub::Min(), scram::mef::UniformDeviate::Validate(), scram::mef::NormalDeviate::Validate(), Validate(), and scram::mef::LogNormalDeviate::Validate().
void scram::mef::Expression::Reset () virtual noexcept
This routine resets the sampling to get new values.
All the arguments are called to reset themselves. If this expression was not sampled, its arguments are not going to get any calls.
Definition at line 41 of file expression.cc.
Referenced by Validate().
bool scram::mef::Expression::IsConstant () virtual noexcept
Determines if the value of the expression varies.
The default logic is to check arguments with uncertainties for sampling. Derived expression classes must decide if they don't have arguments, or if they are random deviates.
Returns
true if the expression's value does not need sampling.
false if the expression's value has uncertainties.
Warning
Improper registration of arguments may yield silent failure.
Reimplemented in scram::mef::ConstantExpression, and scram::mef::RandomDeviate.
Definition at line 49 of file expression.cc.
Referenced by Validate().
virtual double scram::mef::Expression::Max () inline virtual noexcept
Returns
Maximum value of this expression.
Reimplemented in scram::mef::Histogram, scram::mef::BetaDeviate, scram::mef::Div, scram::mef::GammaDeviate, scram::mef::Mul, scram::mef::WeibullExpression, scram::mef::LogNormalDeviate, scram::mef::Sub, scram::mef::GlmExpression, scram::mef::NormalDeviate, scram::mef::Parameter, scram::mef::Add, scram::mef::UniformDeviate, scram::mef::ExponentialExpression, and scram::mef::Neg.
Definition at line 113 of file expression.h.
References Mean().
Referenced by scram::mef::ExponentialExpression::Max(), scram::mef::Add::Max(), scram::mef::Parameter::Max(), scram::mef::Sub::Max(), scram::mef::LogNormalDeviate::Max(), scram::mef::GammaDeviate::Max(), scram::mef::BetaDeviate::Max(), scram::mef::LogNormalDeviate::Mean(), scram::mef::GammaDeviate::Mean(), scram::mef::BetaDeviate::Mean(), scram::mef::Neg::Min(), scram::mef::Sub::Min(), scram::mef::UniformDeviate::Validate(), scram::mef::GlmExpression::Validate(), scram::mef::LogNormalDeviate::Validate(), and scram::mef::WeibullExpression::Validate().
virtual double scram::mef::Expression::Min () inline virtual noexcept
Returns
Minimum value of this expression.
Reimplemented in scram::mef::Histogram, scram::mef::BetaDeviate, scram::mef::Div, scram::mef::GammaDeviate, scram::mef::Mul, scram::mef::WeibullExpression, scram::mef::LogNormalDeviate, scram::mef::Sub, scram::mef::NormalDeviate, scram::mef::GlmExpression, scram::mef::Parameter, scram::mef::Add, scram::mef::UniformDeviate, scram::mef::ExponentialExpression, and scram::mef::Neg.
Definition at line 116 of file expression.h.
References Mean().
Referenced by scram::mef::Neg::Max(), scram::mef::Sub::Max(), scram::mef::ExponentialExpression::Min(), scram::mef::Add::Min(), scram::mef::Parameter::Min(), scram::mef::Sub::Min(), scram::mef::ExponentialExpression::Validate(), scram::mef::UniformDeviate::Validate(), scram::mef::NormalDeviate::Validate(), scram::mef::GlmExpression::Validate(), scram::mef::LogNormalDeviate::Validate(), scram::mef::WeibullExpression::Validate(), scram::mef::GammaDeviate::Validate(), and scram::mef::BetaDeviate::Validate().
void scram::mef::Expression::AddArg (const ExpressionPtr & arg) inline protected
Registers an additional argument expression.
Parameters
[in] arg An argument expression used by this expression.
Definition at line 122 of file expression.h.
Referenced by scram::mef::Parameter::expression(), and scram::mef::Histogram::Histogram().
The documentation for this class was generated from the following files:
expression.h
expression.cc