scram::core::ProbabilityAnalyzer< Bdd > Class Template Reference
scram::core::ProbabilityAnalyzer< Bdd > Class Template Reference
Specialization of probability analyzer with Binary Decision Diagrams.
#include <probability_analysis.h>
Public Member Functions
template<class Algorithm >
ProbabilityAnalyzer (const FaultTreeAnalyzer< Algorithm > *fta)
Constructs probability analyzer from a fault tree analyzer with the same algorithm.
ProbabilityAnalyzer (FaultTreeAnalyzer< Bdd > *fta)
Reuses BDD structures from Fault tree analyzer.
~ProbabilityAnalyzer () noexcept
Deletes the Boolean graph and BDD only if ProbabilityAnalyzer is the owner of them.
Bdd * bdd_graph ()
double CalculateTotalProbability (const std::vector< double > &p_vars) noexcept
Calculates the total probability with a different set of probability values than the one given upon construction.
Public Member Functions inherited from scram::core::ProbabilityAnalyzerBase
template<class Algorithm >
ProbabilityAnalyzerBase (const FaultTreeAnalyzer< Algorithm > *fta)
Constructs probability analyzer from a fault tree analyzer.
const BooleanGraph * graph () const
const std::vector< Product > & products () const
const std::vector< double > & p_vars () const
Public Member Functions inherited from scram::core::ProbabilityAnalysis
ProbabilityAnalysis (const FaultTreeAnalysis *fta)
Probability analysis with the results of qualitative analysis.
void Analyze () noexcept
Performs quantitative analysis on the supplied fault tree.
double p_total () const
Public Member Functions inherited from scram::core::Analysis
Analysis (const Settings &settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Additional Inherited Members
Public Types inherited from scram::core::ProbabilityAnalyzerBase
using Product = std::vector< int >
Alias for clarity.
Protected Member Functions inherited from scram::core::Analysis
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
template<>
class scram::core::ProbabilityAnalyzer< Bdd >
Specialization of probability analyzer with Binary Decision Diagrams.
The quantitative analysis is done with BDD.
Definition at line 219 of file probability_analysis.h.
Constructor & Destructor Documentation
template<class Algorithm > scram::core::ProbabilityAnalyzer< Bdd >::ProbabilityAnalyzer (const FaultTreeAnalyzer< Algorithm > * fta) inline explicit
Constructs probability analyzer from a fault tree analyzer with the same algorithm.
Template Parameters
Algorithm Fault tree analysis algorithm.
Parameters
[in] fta Finished fault tree analyzer with results.
Definition at line 228 of file probability_analysis.h.
scram::core::ProbabilityAnalyzer< Bdd >::ProbabilityAnalyzer (FaultTreeAnalyzer< Bdd > * fta) explicit
Reuses BDD structures from Fault tree analyzer.
Parameters
[in] fta Finished fault tree analyzer with BDD algorithms.
Precondition
BDD is fully formed and used.
Postcondition
FaultTreeAnalyzer is not corrupted by use of its BDD internals.
Definition at line 95 of file probability_analysis.cc.
References scram::core::FaultTreeAnalyzer< Algorithm >::algorithm(), scram::DEBUG2, LOG, and scram::core::Ite::Ptr().
scram::core::ProbabilityAnalyzer< Bdd >::~ProbabilityAnalyzer () noexcept
Deletes the Boolean graph and BDD only if ProbabilityAnalyzer is the owner of them.
Definition at line 104 of file probability_analysis.cc.
Member Function Documentation
Bdd* scram::core::ProbabilityAnalyzer< Bdd >::bdd_graph () inline
Returns
Binary decision diagram used for calculations.
Definition at line 250 of file probability_analysis.h.
References scram::core::CalculateProbability(), and scram::core::ProbabilityAnalyzerBase::p_vars().
double scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability (const std::vector< double > & p_vars) noexcept
Calculates the total probability with a different set of probability values than the one given upon construction.
Parameters
[in] p_vars A map of probabilities of the graph variables. The indices of the variables must map exactly to the vector indices.
Returns
The total probability calculated with the given values.
Definition at line 109 of file probability_analysis.cc.
References scram::core::Analysis::AddAnalysisTime(), scram::core::CalculateProbability(), scram::core::Settings::ccf_analysis(), CLOCK, scram::core::Bdd::Function::complement, scram::DEBUG2, scram::DEBUG4, DUR, LOG, scram::core::ProbabilityAnalyzerBase::p_vars(), scram::core::Ite::Ptr(), scram::core::Preprocessor::Run(), scram::core::Analysis::settings(), scram::core::FaultTreeAnalysis::top_event(), and scram::core::Bdd::Function::vertex.
The documentation for this class was generated from the following files:
probability_analysis.h
probability_analysis.cc