scram::mef::Id Class Reference
scram::mef::Id Class Reference
Mixin class for assigning unique identifiers to elements.
#include <element.h>
Public Member Functions
Id (const Element &el, const Role &role)
Mangles the element name to be unique.
const std::string & id () const
Detailed Description
Mixin class for assigning unique identifiers to elements.
Definition at line 173 of file element.h.
Constructor & Destructor Documentation
scram::mef::Id::Id (const Element & el, const Role & role)
Mangles the element name to be unique.
Private elements get their full path as their ids, while public elements retain their name as ids.
Parameters
[in] el The owner of the id.
[in] role The role of the element.
Exceptions
LogicError The name mangling strings are empty.
Definition at line 82 of file element.cc.
References scram::mef::Role::base_path(), scram::mef::Element::name(), and scram::mef::Role::role().
Referenced by scram::mef::Parameter::Parameter().
Member Function Documentation
const std::string& scram::mef::Id::id () const inline
Returns
The unique id that is set upon the construction of this element.
Definition at line 186 of file element.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
The documentation for this class was generated from the following files:
element.h
element.cc