scram::mef::WeibullExpression Class Reference
scram::mef::WeibullExpression Class Reference
Weibull distribution with scale, shape, time shift, and time.
#include <exponential.h>
Public Member Functions
WeibullExpression (const ExpressionPtr &alpha, const ExpressionPtr &beta, const ExpressionPtr &t0, const ExpressionPtr &time)
Constructor for Weibull distribution.
void Validate () const override
Validates the expression.
double Mean () noexceptoverride
double Max () noexceptoverride
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args)
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual bool IsConstant () noexcept
Determines if the value of the expression varies.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
Weibull distribution with scale, shape, time shift, and time.
Definition at line 107 of file exponential.h.
Constructor & Destructor Documentation
scram::mef::WeibullExpression::WeibullExpression (const ExpressionPtr & alpha, const ExpressionPtr & beta, const ExpressionPtr & t0, const ExpressionPtr & time)
Constructor for Weibull distribution.
Parameters
[in] alpha Scale parameter.
[in] beta Shape parameter.
[in] t0 Time shift.
[in] time Mission time.
Definition at line 91 of file exponential.cc.
Member Function Documentation
void scram::mef::WeibullExpression::Validate () const override virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
InvalidArgument The arguments are invalid for setup.
Reimplemented from scram::mef::Expression.
Definition at line 101 of file exponential.cc.
References scram::mef::Expression::Max(), scram::mef::Expression::Mean(), and scram::mef::Expression::Min().
double scram::mef::WeibullExpression::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 120 of file exponential.h.
double scram::mef::WeibullExpression::Max () inline override virtual noexcept
Returns
Maximum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 124 of file exponential.h.
double scram::mef::WeibullExpression::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 128 of file exponential.h.
The documentation for this class was generated from the following files:
exponential.h
exponential.cc