scram::mef::Parameter Class Reference
scram::mef::Parameter Class Reference
This class provides a representation of a variable in basic event description.
#include <parameter.h>
Public Member Functions
Parameter (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Creates a parameter as a variable for future references.
void expression (const ExpressionPtr &expression)
Sets the expression of this parameter.
Units unit () const
void unit (Units unit)
Sets the unit of this parameter.
bool unused ()
void unused (bool state)
Sets the usage state for this parameter.
double Mean () noexceptoverride
double Max () noexceptoverride
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args)
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
virtual void Validate () const
Validates the expression.
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual bool IsConstant () noexcept
Determines if the value of the expression varies.
Public Member Functions inherited from scram::mef::Element
Element (std::string name, bool optional_name=false)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string new_label)
Sets the label.
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Public Member Functions inherited from scram::mef::Id
Id (const Element &el, const Role &role)
Mangles the element name to be unique.
const std::string & id () const
Public Member Functions inherited from scram::mef::NodeMark
Mark mark () const
void mark (Mark label)
Sets the mark for this node.
Additional Inherited Members
Public Types inherited from scram::mef::NodeMark
enum Mark : std::uint8_t { kClear = 0, kTemporary, kPermanent }
Possible marks for the node.
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
This class provides a representation of a variable in basic event description.
It is both expression and element description.
Definition at line 36 of file parameter.h.
Constructor & Destructor Documentation
scram::mef::Parameter::Parameter (std::string name, std::string base_path = "", RoleSpecifier role = RoleSpecifier::kPublic) explicit
Creates a parameter as a variable for future references.
Parameters
[in] name The name of this variable (Case sensitive).
[in] base_path The series of containers to get this parameter.
[in] role The role of the parameter within the model or container.
Exceptions
LogicError The name is empty.
InvalidArgument The name or reference paths are malformed.
Definition at line 28 of file parameter.cc.
References scram::mef::Role::base_path(), scram::mef::Element::Element(), scram::mef::Id::Id(), scram::mef::Element::name(), scram::mef::Role::Role(), and scram::mef::Role::role().
Member Function Documentation
void scram::mef::Parameter::expression (const ExpressionPtr & expression)
Sets the expression of this parameter.
Parameters
[in] expression The expression to describe this parameter.
Exceptions
LogicError The parameter expression is already set.
Definition at line 38 of file parameter.cc.
References scram::mef::Expression::AddArg().
Referenced by scram::mef::Initializer::Initializer().
Units scram::mef::Parameter::unit () const inline
Returns
The unit of this parameter.
Definition at line 61 of file parameter.h.
void scram::mef::Parameter::unit (Units unit) inline
Sets the unit of this parameter.
Parameters
[in] unit A valid unit.
Definition at line 66 of file parameter.h.
References unit().
Referenced by unit().
bool scram::mef::Parameter::unused () inline
Returns
The usage state of this parameter.
Definition at line 69 of file parameter.h.
void scram::mef::Parameter::unused (bool state) inline
Sets the usage state for this parameter.
Parameters
[in] state The usage state for this parameter.
Definition at line 74 of file parameter.h.
double scram::mef::Parameter::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 76 of file parameter.h.
References scram::mef::Expression::Mean().
double scram::mef::Parameter::Max () inline override virtual noexcept
Returns
Maximum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 77 of file parameter.h.
References scram::mef::Expression::Max().
double scram::mef::Parameter::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 78 of file parameter.h.
References scram::mef::Expression::Min(), and scram::mef::Expression::Sample().
The documentation for this class was generated from the following files:
parameter.h
parameter.cc