scram::core::ImportanceAnalysis Class Reference
scram::core::ImportanceAnalysis Class Reference abstract
Analysis of importance factors of risk model variables.
#include <importance_analysis.h>
Public Types
using ImportanceRecord = std::pair< const mef::BasicEvent *, ImportanceFactors >
Mapping of an event and its importance.
Public Member Functions
ImportanceAnalysis (const ProbabilityAnalysis *prob_analysis)
Importance analysis on the fault tree represented by its probability analysis.
void Analyze () noexcept
Performs quantitative analysis of importance factors of basic events in products.
const std::unordered_map< std::string, ImportanceFactors > & importance () const
const std::vector< ImportanceRecord > & important_events () const
Public Member Functions inherited from scram::core::Analysis
Analysis (const Settings &settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Protected Member Functions
std::vector< std::pair< int, const mef::BasicEvent * > > GatherImportantEvents (const BooleanGraph *graph, const std::vector< std::vector< int >> &products) noexcept
Gathers all events present in products.
Protected Member Functions inherited from scram::core::Analysis
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Analysis of importance factors of risk model variables.
Definition at line 52 of file importance_analysis.h.
Constructor & Destructor Documentation
scram::core::ImportanceAnalysis::ImportanceAnalysis (const ProbabilityAnalysis * prob_analysis) explicit
Importance analysis on the fault tree represented by its probability analysis.
Parameters
[in] prob_analysis Completed probability analysis.
Definition at line 33 of file importance_analysis.cc.
Member Function Documentation
void scram::core::ImportanceAnalysis::Analyze () noexcept
Performs quantitative analysis of importance factors of basic events in products.
Precondition
Analysis is called only once.
Definition at line 36 of file importance_analysis.cc.
References scram::core::Analysis::AddAnalysisTime(), scram::core::ImportanceFactors::cif, CLOCK, scram::DEBUG3, scram::core::ImportanceFactors::dif, DUR, GatherImportantEvents(), LOG, scram::core::ImportanceFactors::mif, scram::core::ImportanceFactors::raw, and scram::core::ImportanceFactors::rrw.
Referenced by scram::core::RiskAnalysis::Analyze().
const std::unordered_map<std::string, ImportanceFactors>& scram::core::ImportanceAnalysis::importance () const inline
Returns
Map with basic events and their importance factors.
Precondition
The importance analysis is done.
Definition at line 75 of file importance_analysis.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::vector<ImportanceRecord>& scram::core::ImportanceAnalysis::important_events () const inline
Returns
A collection of important events and their importance factors.
Precondition
The importance analysis is done.
Definition at line 82 of file importance_analysis.h.
Referenced by GatherImportantEvents(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
std::vector< std::pair< int, const mef::BasicEvent * > > scram::core::ImportanceAnalysis::GatherImportantEvents (const BooleanGraph * graph, const std::vector< std::vector< int >> & products) protected noexcept
Gathers all events present in products.
Only this events can have importance factors.
Parameters
[in] graph Boolean graph with basic event indices and pointers.
[in] products Products with basic event indices.
Returns
A unique collection of important basic events.
Definition at line 58 of file importance_analysis.cc.
References scram::core::Bdd::Function::complement, scram::core::BooleanGraph::GetBasicEvent(), important_events(), scram::core::Ite::Ptr(), and scram::core::Bdd::Function::vertex.
Referenced by Analyze().
The documentation for this class was generated from the following files:
importance_analysis.h
importance_analysis.cc