scram::XmlStreamElement Class Reference
scram::XmlStreamElement Class Reference
Writer of data formed as an XML element to a stream.
#include <xml_stream.h>
Public Member Functions
XmlStreamElement (const char *name, std::ostream &out)
Constructs a root streamer for the XML element data ready to accept attributes, elements, text.
XmlStreamElement (XmlStreamElement &&)
Move constructor is only declared to make the compiler happy.
~XmlStreamElement () noexcept
Puts the closing tag.
template<typename T >
XmlStreamElement & SetAttribute (const char *name, T &&value)
Sets the attributes for the element.
template<typename T >
void AddText (T &&text)
Adds text to the element.
XmlStreamElement AddChild (const char *name)
Adds a child element to the element.
Detailed Description
Writer of data formed as an XML element to a stream.
This class relies on the RAII to put the closing tags. It is designed for stack-based use so that its destructor gets called at scope exit. One element at a time must be operated. The output will be malformed if two child elements at the same scope are being streamed. To prevent this from happening, the parent element is put into an inactive state while its child element is alive.
Note
The stream is designed to prevent mixing XML text and elements due to the absence of the use case or need. However, there's no fundamental design or technical issue restricting the introduction of this feature. As a workaround, markup elements in the text (e.g., <br/>) can be fed directly as a raw text.
Warning
The names of elements and contents of XML data are NOT fully validated to be proper XML. It is up to the caller to sanitize the input text.
The API works with C strings, but this class does not manage the string lifetime. It doesn't own any strings. The provider of the strings must make sure the lifetime of the string is long enough for streaming. It is the most common case that strings are literals, so there's no need to worry about dynamic lifetime.
Definition at line 65 of file xml_stream.h.
Constructor & Destructor Documentation
scram::XmlStreamElement::XmlStreamElement (const char * name, std::ostream & out)
Constructs a root streamer for the XML element data ready to accept attributes, elements, text.
Parameters
[in] name Non-empty string name for the element.
[in,out] out The destination stream.
Exceptions
XmlStreamError Invalid setup for the element.
Definition at line 29 of file xml_stream.cc.
Referenced by AddChild().
scram::XmlStreamElement::XmlStreamElement (XmlStreamElement &&)
Move constructor is only declared to make the compiler happy.
The code must rely on the RVO, NRVO, and copy elision instead of this constructor.
The constructor is not defined, so the use of this constructor will produce a linker error.
scram::XmlStreamElement::~XmlStreamElement () noexcept
Puts the closing tag.
Precondition
No child element is alive.
Warning
The output will be malformed if the child outlives the parent. It can happen if the destructor is called explicitly, or if the objects are allocated on the heap with different lifetimes.
Definition at line 55 of file xml_stream.cc.
Member Function Documentation
template<typename T > XmlStreamElement& scram::XmlStreamElement::SetAttribute (const char * name, T && value) inline
Sets the attributes for the element.
Template Parameters
T Streamable type supporting operator<<.
Parameters
[in] name Non-empty name for the attribute.
[in] value The value of the attribute.
Returns
The reference to this element.
Exceptions
XmlStreamError Invalid setup for the attribute.
Definition at line 107 of file xml_stream.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::FaultTreeAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ProbabilityAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::Reporter::ReportCalculatedQuantity< core::UncertaintyAnalysis >().
template<typename T > void scram::XmlStreamElement::AddText (T && text) inline
Adds text to the element.
Template Parameters
T Streamable type supporting operator<<.
Parameters
[in] text Non-empty text.
Postcondition
No more elements or attributes can be added.
More text can be added.
Exceptions
XmlStreamError Invalid setup or state for text addition.
Definition at line 130 of file xml_stream.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::FaultTreeAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ProbabilityAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::Reporter::ReportCalculatedQuantity< core::UncertaintyAnalysis >().
XmlStreamElement scram::XmlStreamElement::AddChild (const char * name)
Adds a child element to the element.
Parameters
[in] name Non-empty name for the child element.
Returns
A streamer for child element.
Precondition
The child element will be destroyed before the parent.
Postcondition
The parent element is inactive while the child element is alive.
Exceptions
XmlStreamError Invalid setup or state for element addition.
Definition at line 72 of file xml_stream.cc.
References XmlStreamElement().
Referenced by scram::Reporter::Report(), scram::Reporter::ReportCalculatedQuantity< core::FaultTreeAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::ProbabilityAnalysis >(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), and scram::Reporter::ReportCalculatedQuantity< core::UncertaintyAnalysis >().
The documentation for this class was generated from the following files:
xml_stream.h
xml_stream.cc