scram::core::CutSetProbabilityCalculator Class Reference
scram::core::CutSetProbabilityCalculator Class Reference
Quantitative calculator of a probability value of a single cut set.
#include <probability_analysis.h>
Public Types
using CutSet = std::vector< int >
Alias for clarity.
Public Member Functions
double Calculate (const CutSet &cut_set, const std::vector< double > &p_vars) noexcept
Calculates a probability of a cut set, whose members are in AND relationship with each other.
double CheckUnity (const std::vector< CutSet > &cut_sets) noexcept
Checks the special case of a unity set with probability 1.
Detailed Description
Quantitative calculator of a probability value of a single cut set.
Definition at line 68 of file probability_analysis.h.
Member Function Documentation
double scram::core::CutSetProbabilityCalculator::Calculate (const CutSet & cut_set, const std::vector< double > & p_vars) noexcept
Calculates a probability of a cut set, whose members are in AND relationship with each other.
This function assumes independence of each member.
Parameters
[in] cut_set A cut set with positive indices of basic events.
[in] p_vars Probabilities of events mapped to a vector.
Returns
The total probability of the cut set.
Precondition
The cut set doesn't contain complements.
Probability values are non-negative.
Indices of events directly map to vector indices.
Definition at line 49 of file probability_analysis.cc.
Referenced by scram::core::RareEventCalculator::Calculate(), and scram::core::McubCalculator::Calculate().
double scram::core::CutSetProbabilityCalculator::CheckUnity (const std::vector< CutSet > & cut_sets) inline noexcept
Checks the special case of a unity set with probability 1.
Parameters
[in] cut_sets Collection of ALL cut sets.
Returns
true if the Unity set is detected.
Precondition
The unity set is indicated by a single empty set.
Provided cut sets are ALL the cut sets under consideration.
Definition at line 95 of file probability_analysis.h.
Referenced by scram::core::RareEventCalculator::Calculate(), and scram::core::McubCalculator::Calculate().
The documentation for this class was generated from the following files:
probability_analysis.h
probability_analysis.cc