scram::core::Settings Class Reference
scram::core::Settings Class Reference
Builder for analysis settings.
#include <settings.h>
Public Member Functions
const std::string & algorithm () const
Settings & algorithm (const std::string &algorithm)
Sets the algorithm for Qualitative analysis.
bool prime_implicants () const
Settings & prime_implicants (bool flag)
Sets a flag to calculate prime implicants instead of minimal cut sets.
int limit_order () const
Settings & limit_order (int order)
Sets the limit order for products.
double cut_off () const
Settings & cut_off (double prob)
Sets the cut-off probability for products to be considered for analysis.
const std::string & approximation () const
Settings & approximation (const std::string &approx)
Sets the approximation for quantitative analysis.
int num_trials () const
Settings & num_trials (int n)
Sets the number of trials for Monte Carlo simulations.
int num_quantiles () const
Settings & num_quantiles (int n)
Sets the number of quantiles for distributions.
int num_bins () const
Settings & num_bins (int n)
Sets the number of bins for histograms.
int seed () const
Settings & seed (int s)
Sets the seed for the pseudo-random number generator.
double mission_time () const
Settings & mission_time (double time)
Sets the system mission time.
bool probability_analysis () const
Settings & probability_analysis (bool flag)
Sets the flag for probability analysis.
bool importance_analysis () const
Settings & importance_analysis (bool flag)
Sets the flag for importance analysis.
bool uncertainty_analysis () const
Settings & uncertainty_analysis (bool flag)
Sets the flag for uncertainty analysis.
bool ccf_analysis () const
Settings & ccf_analysis (bool flag)
Sets the flag for CCF analysis.
Public Attributes
bool preprocessor = false
Stop analysis after preprocessor.
bool print = false
Print analysis results in a terminal friendly way.
Detailed Description
Builder for analysis settings.
Analysis facilities are guaranteed not to throw or fail with an instance of this class.
Warning
Some settings with defaults and constraints may have side-effects on other settings.
The order of building the settings matters.
Definition at line 37 of file settings.h.
Member Function Documentation
const std::string& scram::core::Settings::algorithm () const inline
Returns
The Qualitative analysis algorithm.
Definition at line 40 of file settings.h.
Referenced by algorithm(), scram::core::RiskAnalysis::Analyze(), and scram::Config::Config().
Settings & scram::core::Settings::algorithm (const std::string & algorithm)
Sets the algorithm for Qualitative analysis.
Appropriate defaults are given to other settings relevant to the algorithm.
MOCUS and ZBDD based analyses run with the Rare-Event approximation by default. Whereas, BDD based analyses run with exact quantitative analysis.
Parameters
[in] algorithm The name of the algorithm in lower case.
Returns
Reference to this object.
Exceptions
InvalidArgument The algorithm is not recognized.
Definition at line 28 of file settings.cc.
References algorithm(), approximation(), and prime_implicants().
bool scram::core::Settings::prime_implicants () const inline
Returns
true if prime implicants are to be calculated instead of minimal cut sets.
Definition at line 59 of file settings.h.
Referenced by algorithm(), scram::Config::Config(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Zbdd::Minimize(), and scram::core::Zbdd::Zbdd().
Settings & scram::core::Settings::prime_implicants (bool flag)
Sets a flag to calculate prime implicants instead of minimal cut sets.
Prime implicants can only be calculated with BDD-based algorithms.
The request for prime implicants cancels the request for inapplicable quantitative analysis approximations.
Parameters
[in] flag True for the request.
Returns
Reference to this object.
Exceptions
InvalidArgument The request is not relevant to the algorithm.
Definition at line 45 of file settings.cc.
References approximation().
int scram::core::Settings::limit_order () const inline
Returns
The limit on the size of products.
Definition at line 75 of file settings.h.
Referenced by scram::core::Zbdd::Analyze(), scram::Config::Config(), scram::core::FaultTreeAnalysis::Convert(), scram::core::zbdd::CutSetContainer::ConvertGate(), scram::core::Zbdd::EliminateComplements(), scram::core::Zbdd::EliminateConstantModules(), scram::core::zbdd::CutSetContainer::ExpandGate(), scram::core::Zbdd::FindOrAddVertex(), scram::core::Zbdd::GatherModules(), scram::core::zbdd::CutSetContainer::Merge(), scram::core::Mocus::products(), and scram::core::Zbdd::Zbdd().
Settings & scram::core::Settings::limit_order (int order)
Sets the limit order for products.
Parameters
[in] order A natural number for the limit order.
Returns
Reference to this object.
Exceptions
InvalidArgument The number is less than 0 or too large.
Definition at line 55 of file settings.cc.
double scram::core::Settings::cut_off () const inline
Returns
The minimum required probability for products.
Definition at line 87 of file settings.h.
Referenced by scram::Config::Config().
Settings & scram::core::Settings::cut_off (double prob)
Sets the cut-off probability for products to be considered for analysis.
Parameters
[in] prob The minimum probability for products.
Returns
Reference to this object.
Exceptions
InvalidArgument The probability is not in the [0, 1] range.
Definition at line 63 of file settings.cc.
const std::string& scram::core::Settings::approximation () const inline
Returns
"no" if no quantitative approximation is requested.
"rare-event" for the rare-event approximation.
"mcub" for the min-cut-upper bound approximation.
Definition at line 102 of file settings.h.
Referenced by algorithm(), scram::core::RiskAnalysis::Analyze(), scram::Config::Config(), and prime_implicants().
Settings & scram::core::Settings::approximation (const std::string & approx)
Sets the approximation for quantitative analysis.
Parameters
[in] approx Approximation to be applied.
Returns
Reference to this object.
Exceptions
InvalidArgument The approximation is not recognized or inappropriate for analysis.
Definition at line 71 of file settings.cc.
int scram::core::Settings::num_trials () const inline
Returns
The number of trials for Monte-Carlo simulations.
Definition at line 115 of file settings.h.
Referenced by scram::Config::Config(), and scram::core::UncertaintyAnalysis::SampleEventProbabilities().
Settings & scram::core::Settings::num_trials (int n)
Sets the number of trials for Monte Carlo simulations.
Parameters
[in] n A natural number for the number of trials.
Returns
Reference to this object.
Exceptions
InvalidArgument The number is less than 1.
Definition at line 83 of file settings.cc.
int scram::core::Settings::num_quantiles () const inline
Returns
The number of quantiles for distributions.
Definition at line 127 of file settings.h.
Referenced by scram::Config::Config(), and scram::core::UncertaintyAnalysis::SampleEventProbabilities().
Settings & scram::core::Settings::num_quantiles (int n)
Sets the number of quantiles for distributions.
Parameters
[in] n A natural number for the number of quantiles.
Returns
Reference to this object.
Exceptions
InvalidArgument The number is less than 1.
Definition at line 91 of file settings.cc.
int scram::core::Settings::num_bins () const inline
Returns
The number of bins for histograms.
Definition at line 139 of file settings.h.
Referenced by scram::Config::Config().
Settings & scram::core::Settings::num_bins (int n)
Sets the number of bins for histograms.
Parameters
[in] n A natural number for the number of bins.
Returns
Reference to this object.
Exceptions
InvalidArgument The number is less than 1.
Definition at line 99 of file settings.cc.
int scram::core::Settings::seed () const inline
Returns
The seed of the pseudo-random number generator.
Definition at line 151 of file settings.h.
Referenced by scram::Config::Config().
Settings & scram::core::Settings::seed (int s)
Sets the seed for the pseudo-random number generator.
Parameters
[in] s A positive number.
Returns
Reference to this object.
Exceptions
InvalidArgument The number is negative.
Definition at line 107 of file settings.cc.
double scram::core::Settings::mission_time () const inline
Returns
The length time of the system under risk.
Definition at line 163 of file settings.h.
Referenced by scram::Config::Config().
Settings & scram::core::Settings::mission_time (double time)
Sets the system mission time.
Parameters
[in] time A positive number in hours by default.
Returns
Reference to this object.
Exceptions
InvalidArgument The time value is negative.
Definition at line 115 of file settings.cc.
bool scram::core::Settings::probability_analysis () const inline
Returns
true if probability analysis is requested.
Definition at line 175 of file settings.h.
Referenced by scram::Config::Config(), scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
Settings& scram::core::Settings::probability_analysis (bool flag) inline
Sets the flag for probability analysis.
If another analysis requires probability analysis, it won't be possible to turn off probability analysis before the parent analysis.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 185 of file settings.h.
bool scram::core::Settings::importance_analysis () const inline
Returns
true if importance analysis is requested.
Definition at line 192 of file settings.h.
Referenced by scram::Config::Config(), scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
Settings& scram::core::Settings::importance_analysis (bool flag) inline
Sets the flag for importance analysis.
Importance analysis is performed together with probability analysis. Appropriate flags are turned on.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 202 of file settings.h.
bool scram::core::Settings::uncertainty_analysis () const inline
Returns
true if uncertainty analysis is requested.
Definition at line 210 of file settings.h.
Referenced by scram::Config::Config(), scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
Settings& scram::core::Settings::uncertainty_analysis (bool flag) inline
Sets the flag for uncertainty analysis.
Uncertainty analysis implies probability analysis, so the probability analysis is turned on implicitly.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 219 of file settings.h.
bool scram::core::Settings::ccf_analysis () const inline
Returns
true if CCF groups must be incorporated into analysis.
Definition at line 227 of file settings.h.
Referenced by scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability(), and scram::Config::Config().
Settings& scram::core::Settings::ccf_analysis (bool flag) inline
Sets the flag for CCF analysis.
Parameters
[in] flag True or false for turning on or off the analysis.
Returns
Reference to this object.
Definition at line 234 of file settings.h.
The documentation for this class was generated from the following files:
settings.h
settings.cc