scram::mef::Component Class Reference
scram::mef::Component Class Reference
Component is for logical grouping of events, gates, and other components.
#include <fault_tree.h>
Public Member Functions
Component (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs a component assuming that it exists within some fault tree.
void AddGate (const GatePtr &gate)
Adds a gate into this component container.
void AddBasicEvent (const BasicEventPtr &basic_event)
Adds a basic event into this component container.
void AddHouseEvent (const HouseEventPtr &house_event)
Adds a house event into this component container.
void AddParameter (const ParameterPtr &parameter)
Adds a parameter into this component container.
void AddCcfGroup (const CcfGroupPtr &ccf_group)
Adds a CCF group and its members into this component container.
void AddComponent (std::unique_ptr< Component > component)
Adds a member component container into this component container.
const ElementTable< GatePtr > & gates () const
const ElementTable< BasicEventPtr > & basic_events () const
const ElementTable< HouseEventPtr > & house_events () const
const ElementTable< ParameterPtr > & parameters () const
const ElementTable< CcfGroupPtr > & ccf_groups () const
const ElementTable< std::unique_ptr< Component > > & components () const
Public Member Functions inherited from scram::mef::Element
Element (std::string name, bool optional_name=false)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string new_label)
Sets the label.
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Protected Member Functions
void GatherGates (std::unordered_set< Gate * > *gates)
Recursively traverses components to gather gates relevant to the whole component.
Detailed Description
Component is for logical grouping of events, gates, and other components.
Definition at line 40 of file fault_tree.h.
Constructor & Destructor Documentation
scram::mef::Component::Component (std::string name, std::string base_path = "", RoleSpecifier role = RoleSpecifier::kPublic) explicit
Constructs a component assuming that it exists within some fault tree.
The public or private role of a component is not for the components itself, but for the events and parameters of the component. Component name is not meant to be public; however, it must be unique within the parent fault tree or component.
Parameters
[in] name The name identifier for the component.
[in] base_path The series of containers to get this container.
[in] role The default role for container members.
Exceptions
LogicError The name is empty.
InvalidArgument The name or reference paths are malformed.
Definition at line 28 of file fault_tree.cc.
Member Function Documentation
const ElementTable<GatePtr>& scram::mef::Component::gates () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 64 of file fault_tree.h.
Referenced by scram::mef::FaultTree::CollectTopEvents(), components(), and scram::mef::FaultTree::top_events().
const ElementTable<BasicEventPtr>& scram::mef::Component::basic_events () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 65 of file fault_tree.h.
const ElementTable<HouseEventPtr>& scram::mef::Component::house_events () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 68 of file fault_tree.h.
const ElementTable<ParameterPtr>& scram::mef::Component::parameters () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 71 of file fault_tree.h.
const ElementTable<CcfGroupPtr>& scram::mef::Component::ccf_groups () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 72 of file fault_tree.h.
const ElementTable<std::unique_ptr<Component> >& scram::mef::Component::components () const inline
Returns
The container of component constructs of specific kind with construct original names as keys.
Definition at line 73 of file fault_tree.h.
References AddBasicEvent(), AddCcfGroup(), AddComponent(), AddGate(), AddHouseEvent(), AddParameter(), gates(), and GatherGates().
void scram::mef::Component::AddGate (const GatePtr & gate)
Adds a gate into this component container.
Parameters
[in] gate The gate to be added to this tree.
Exceptions
ValidationError The event is already in this container.
Definition at line 33 of file fault_tree.cc.
Referenced by components(), and scram::mef::Initializer::Initializer().
void scram::mef::Component::AddBasicEvent (const BasicEventPtr & basic_event)
Adds a basic event into this component container.
Parameters
[in] basic_event The basic event to be added to this tree.
Exceptions
ValidationError The event is already in this container.
Definition at line 37 of file fault_tree.cc.
Referenced by components(), and scram::mef::Initializer::Initializer().
void scram::mef::Component::AddHouseEvent (const HouseEventPtr & house_event)
Adds a house event into this component container.
Parameters
[in] house_event The house event to be added to this tree.
Exceptions
ValidationError The event is already in this container.
Definition at line 41 of file fault_tree.cc.
Referenced by components(), and scram::mef::Initializer::Initializer().
void scram::mef::Component::AddParameter (const ParameterPtr & parameter)
Adds a parameter into this component container.
Parameters
[in] parameter The parameter to be added to this tree.
Exceptions
ValidationError The parameter is already in this container.
Definition at line 45 of file fault_tree.cc.
Referenced by components(), and scram::mef::Initializer::Initializer().
void scram::mef::Component::AddCcfGroup (const CcfGroupPtr & ccf_group)
Adds a CCF group and its members into this component container.
Parameters
[in] ccf_group The CCF group to be added to this container.
Exceptions
ValidationError Duplicate CCF groups or duplicate basic event members.
Definition at line 51 of file fault_tree.cc.
References scram::mef::Element::name().
Referenced by components(), and scram::mef::Initializer::Initializer().
void scram::mef::Component::AddComponent (std::unique_ptr< Component > component)
Adds a member component container into this component container.
Components are unique. The ownership is transferred to this component only.
Parameters
[in] component The CCF group to be added to this container.
Exceptions
ValidationError The component is already in this container.
Definition at line 68 of file fault_tree.cc.
Referenced by components(), and scram::mef::Initializer::Initializer().
void scram::mef::Component::GatherGates (std::unordered_set< Gate * > * gates) protected
Recursively traverses components to gather gates relevant to the whole component.
Parameters
[out] gates Gates belonging to this component and its subcomponents.
Definition at line 75 of file fault_tree.cc.
References scram::mef::Element::name().
Referenced by scram::mef::FaultTree::CollectTopEvents(), and components().
The documentation for this class was generated from the following files:
fault_tree.h
fault_tree.cc