scram::mef::Element Class Reference
scram::mef::Element Class Reference
Mixin class that represents any element of analysis that can have extra descriptions, such as attributes and a label.
#include <element.h>
Public Member Functions
Element (std::string name, bool optional_name=false)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string new_label)
Sets the label.
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
Detailed Description
Mixin class that represents any element of analysis that can have extra descriptions, such as attributes and a label.
Definition at line 48 of file element.h.
Constructor & Destructor Documentation
scram::mef::Element::Element (std::string name, bool optional_name = false) explicit
Constructs an element with an original name.
The name is expected to conform to identifier requirements described in the MEF documentation and additions.
Parameters
[in] name The local identifier name.
[in] optional_name Allow empty names.
Exceptions
LogicError The name is required and empty.
InvalidArgument The name is malformed.
Definition at line 31 of file element.cc.
Referenced by scram::mef::Parameter::Parameter().
Member Function Documentation
const std::string& scram::mef::Element::name () const inline
Returns
The original name.
Definition at line 62 of file element.h.
Referenced by scram::mef::Component::AddCcfGroup(), scram::mef::CcfGroup::AddDistribution(), scram::mef::CcfGroup::AddMember(), scram::mef::CcfGroup::ApplyModel(), scram::mef::Component::GatherGates(), GetAttribute(), HasAttribute(), scram::mef::Id::Id(), scram::mef::Initializer::Extractor< Histogram,-1 >::operator()(), scram::mef::Parameter::Parameter(), scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >(), scram::mef::CcfGroup::Validate(), scram::mef::PhiFactorModel::Validate(), scram::mef::Gate::Validate(), and scram::mef::CcfGroup::ValidateDistribution().
const std::string& scram::mef::Element::label () const inline
Returns
The empty or preset label.
Empty string if the label has not been set.
Definition at line 66 of file element.h.
Referenced by scram::mef::Initializer::Initializer().
void scram::mef::Element::label (std::string new_label)
Sets the label.
Parameters
[in] new_label The label to be set.
Exceptions
LogicError The label is already set, or the new label is empty.
Definition at line 39 of file element.cc.
void scram::mef::Element::AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
Parameters
[in] attr Unique attribute of this element.
Exceptions
DuplicateArgumentError A member attribute with the same name already exists.
Postcondition
Pointers or references to existing attributes may get invalidated.
Definition at line 48 of file element.cc.
References HasAttribute(), and scram::mef::Attribute::name.
Referenced by scram::mef::Initializer::Initializer().
bool scram::mef::Element::HasAttribute (const std::string & name) const
Checks if the element has a given attribute.
Parameters
[in] name The identifying name of the attribute.
Returns
true if this element has an attribute with the given name.
Definition at line 57 of file element.cc.
References scram::mef::Attribute::name, and name().
Referenced by AddAttribute(), and scram::mef::Gate::Validate().
const Attribute & scram::mef::Element::GetAttribute (const std::string & name) const
Returns
A member attribute with the given name.
Parameters
[in] name The id name of the attribute.
Exceptions
LogicError There is no such attribute.
Definition at line 63 of file element.cc.
References scram::mef::Attribute::name, and name().
Referenced by scram::mef::Gate::Validate().
The documentation for this class was generated from the following files:
element.h
element.cc