scram::core::Mocus Class Reference
scram::core::Mocus Class Reference
This class analyzes normalized, preprocessed, and indexed fault trees to generate minimal cut sets with the MOCUS algorithm.
#include <mocus.h>
Public Member Functions
Mocus (const BooleanGraph *fault_tree, const Settings &settings)
Prepares a Boolean graph for analysis with the MOCUS algorithm.
void Analyze ()
Finds minimal cut sets from the Boolean graph.
const std::vector< std::vector< int > > & products () const
Detailed Description
This class analyzes normalized, preprocessed, and indexed fault trees to generate minimal cut sets with the MOCUS algorithm.
Definition at line 43 of file mocus.h.
Constructor & Destructor Documentation
scram::core::Mocus::Mocus (const BooleanGraph * fault_tree, const Settings & settings)
Prepares a Boolean graph for analysis with the MOCUS algorithm.
Parameters
[in] fault_tree Preprocessed, normalized, and indexed fault tree.
[in] settings The analysis settings.
Precondition
The passed Boolean graph already has variable ordering.
The Boolean graph is in negation normal form; that is, it contains only positive AND/OR gates.
Definition at line 35 of file mocus.cc.
References scram::core::kNull, and scram::core::BooleanGraph::root().
Member Function Documentation
const std::vector< std::vector< int > > & scram::core::Mocus::products () const
Returns
Generated minimal cut sets with basic event indices.
Definition at line 60 of file mocus.cc.
References scram::core::Gate::args(), scram::core::BooleanGraph::basic_events(), CLOCK, scram::core::Gate::coherent(), scram::DEBUG3, scram::DEBUG4, scram::DEBUG5, DUR, gates, scram::core::Node::index(), scram::core::Settings::limit_order(), LOG, and scram::core::Gate::module().
The documentation for this class was generated from the following files:
mocus.h
mocus.cc