scram::core::Zbdd Class Reference
scram::core::Zbdd Class Reference
Zero-Suppressed Binary Decision Diagrams for set manipulations.
#include <zbdd.h>
Public Types
using VertexPtr = IntrusivePtr< Vertex< SetNode >>
ZBDD vertex base.
using TerminalPtr = IntrusivePtr< Terminal< SetNode >>
Terminal vertex.
Public Member Functions
Zbdd (Bdd *bdd, const Settings &settings) noexcept
Converts Reduced Ordered BDD into Zero-Suppressed BDD.
Zbdd (const BooleanGraph *fault_tree, const Settings &settings) noexcept
Constructor with the analysis target.
void Analyze () noexcept
Runs the analysis with the representation of a Boolean graph as ZBDD.
const std::vector< std::vector< int > > & products () const
Protected Member Functions
Zbdd (const Settings &settings, bool coherent=false, int module_index=0) noexcept
Default constructor to initialize member variables.
const VertexPtr & root () const
void root (const VertexPtr &vertex)
Sets a new root vertex for ZBDD.
const Settings & settings () const
const std::map< int, std::unique_ptr< Zbdd > > & modules () const
void Log () noexcept
Logs properties of the Zbdd.
SetNodePtr FindOrAddVertex (int index, const VertexPtr &high, const VertexPtr &low, int order, bool module=false, bool coherent=false) noexcept
Finds or adds a unique SetNode in the ZBDD.
SetNodePtr FindOrAddVertex (const Gate &gate, const VertexPtr &high, const VertexPtr &low) noexcept
Find or adds a ZBDD SetNode vertex using information from gates.
template<Operator Type>
VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Applies Boolean operation to two vertices representing sets.
VertexPtr Apply (Operator type, const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Applies Boolean operation to two vertices representing sets.
template<Operator Type>
VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Applies Boolean operation to ZBDD graph non-terminal vertices.
VertexPtr EliminateComplements (const VertexPtr &vertex, std::unordered_map< int, VertexPtr > *wide_results) noexcept
Removes complements of variables from products.
void EliminateConstantModules () noexcept
Removes constant modules from products.
VertexPtr Minimize (const VertexPtr &vertex) noexcept
Removes subsets in ZBDD.
int GatherModules (const VertexPtr &vertex, int current_order, std::map< int, std::pair< bool, int >> *modules) noexcept
Traverses ZBDD to find modules and adjusted cut-offs.
void ClearTables () noexcept
Clears all memoization tables.
void ReleaseTables () noexcept
Releases all possible memory from memoization and unique tables.
void JoinModule (int index, std::unique_ptr< Zbdd > container) noexcept
Joins a ZBDD representing a module gate.
template<>
Zbdd::VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Specialization of Apply for AND operator for non-terminal ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Specialization of Apply for AND operator for any ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const SetNodePtr &arg_one, const SetNodePtr &arg_two, int limit_order) noexcept
Specialization of Apply for OR operator for non-terminal ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Specialization of Apply for OR operator for any ZBDD vertices.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Forward declarations of interdependent Apply operation specializations.
template<>
Zbdd::VertexPtr Apply (const VertexPtr &arg_one, const VertexPtr &arg_two, int limit_order) noexcept
Forward declarations of interdependent Apply operation specializations.
Protected Attributes
const TerminalPtr kBase_
Terminal Base (Unity/1) set.
const TerminalPtr kEmpty_
Terminal Empty (Null/0) set.
Detailed Description
Zero-Suppressed Binary Decision Diagrams for set manipulations.
Definition at line 153 of file zbdd.h.
Constructor & Destructor Documentation
scram::core::Zbdd::Zbdd (Bdd * bdd, const Settings & settings) noexcept
Converts Reduced Ordered BDD into Zero-Suppressed BDD.
Parameters
[in] bdd ROBDD with the ITE vertices.
[in] settings Settings for analysis.
Precondition
BDD has attributed edges with only one terminal (1/True).
Postcondition
The input BDD structure is not changed.
Note
The input BDD is not passed as a constant because ZBDD needs BDD facilities to calculate prime implicants. However, ZBDD guarantees to preserve the original BDD structure.
Definition at line 60 of file zbdd.cc.
References CHECK_ZBDD.
Referenced by Zbdd().
scram::core::Zbdd::Zbdd (const BooleanGraph * fault_tree, const Settings & settings) noexcept
Constructor with the analysis target.
ZBDD is directly produced from a Boolean graph.
Parameters
[in] fault_tree Preprocessed, partially normalized, and indexed fault tree.
[in] settings The analysis settings.
Precondition
The passed Boolean graph already has variable ordering.
Note
The construction may take considerable time.
Definition at line 65 of file zbdd.cc.
References begin, CHECK_ZBDD, FindOrAddVertex(), kBase_, kEmpty_, scram::core::kNull, and scram::core::kNullState.
scram::core::Zbdd::Zbdd (const Settings & settings, bool coherent = false, int module_index = 0) explicit protected noexcept
Default constructor to initialize member variables.
Parameters
[in] settings Settings that control analysis complexity.
[in] coherent A flag for coherent modular functions.
[in] module_index The of a module if known.
Definition at line 114 of file zbdd.cc.
References CLOCK, scram::core::Gate::coherent(), scram::core::Bdd::Function::complement, scram::DEBUG2, scram::DEBUG3, scram::DEBUG4, DUR, EliminateComplements(), EliminateConstantModules(), gates, GatherModules(), scram::core::Node::index(), scram::core::Gate::IsConstant(), JoinModule(), scram::core::kNull, scram::core::Settings::limit_order(), LOG, Log(), Minimize(), scram::core::Gate::module(), scram::core::Bdd::modules(), scram::core::Settings::prime_implicants(), scram::core::SetNode::Ptr(), settings(), scram::core::Gate::type(), scram::core::Bdd::Function::vertex, and Zbdd().
Member Function Documentation
void scram::core::Zbdd::Analyze () noexcept
Runs the analysis with the representation of a Boolean graph as ZBDD.
Warning
The analysis will destroy ZBDD.
Postcondition
Products are generated with ZBDD analysis.
Definition at line 89 of file zbdd.cc.
References CLOCK, scram::DEBUG3, scram::DEBUG4, DUR, kEmpty_, scram::core::Settings::limit_order(), LOG, Minimize(), scram::core::SetNode::Ptr(), and ReleaseTables().
const std::vector<std::vector<int> >& scram::core::Zbdd::products () const inline
Returns
Products generated by the analysis.
Definition at line 195 of file zbdd.h.
References scram::core::NonTerminal< SetNode >::coherent().
Referenced by GatherModules().
const VertexPtr& scram::core::Zbdd::root () const inline protected
Returns
Current root vertex of the ZBDD.
Definition at line 207 of file zbdd.h.
Referenced by scram::core::zbdd::CutSetContainer::EliminateComplements(), scram::core::zbdd::CutSetContainer::ExtractIntermediateCutSets(), scram::core::zbdd::CutSetContainer::GatherModules(), scram::core::zbdd::CutSetContainer::GetNextGate(), scram::core::zbdd::CutSetContainer::Merge(), and scram::core::zbdd::CutSetContainer::Minimize().
void scram::core::Zbdd::root (const VertexPtr & vertex) inline protected
Sets a new root vertex for ZBDD.
Parameters
[in] vertex A vertex already registered in this ZBDD.
Definition at line 212 of file zbdd.h.
const Settings& scram::core::Zbdd::settings () const inline protected
Returns
Analysis setting with this ZBDD.
Definition at line 215 of file zbdd.h.
Referenced by scram::core::zbdd::CutSetContainer::ConvertGate(), scram::core::zbdd::CutSetContainer::ExpandGate(), scram::core::zbdd::CutSetContainer::ExtractIntermediateCutSets(), scram::core::zbdd::CutSetContainer::Merge(), and Zbdd().
const std::map<int, std::unique_ptr<Zbdd> >& scram::core::Zbdd::modules () const inline protected
Returns
A set of registered and fully processed modules;
Definition at line 218 of file zbdd.h.
References scram::core::NonTerminal< SetNode >::coherent(), scram::core::NonTerminal< SetNode >::high(), scram::core::NonTerminal< SetNode >::index(), scram::core::NonTerminal< SetNode >::low(), scram::core::NonTerminal< SetNode >::module(), and scram::core::NonTerminal< SetNode >::order().
Referenced by GatherModules(), and scram::core::zbdd::CutSetContainer::GatherModules().
SetNodePtr scram::core::Zbdd::FindOrAddVertex (int index, const VertexPtr & high, const VertexPtr & low, int order, bool module = false, bool coherent = false) protected noexcept
Finds or adds a unique SetNode in the ZBDD.
All vertices in the ZBDD must be created with this functions. Otherwise, the ZBDD may not be reduced, and vertices will miss crucial meta-information about the ZBDD.
Parameters
[in] index Positive or negative index of the node.
[in] high The high vertex.
[in] low The low vertex.
[in] order The order for the vertex variable.
[in] module The indication of a proxy for a modular ZBDD.
[in] coherent The indication of a coherent proxy.
Returns
Set node with the given parameters.
Warning
This function is not aware of reduction rules.
Definition at line 208 of file zbdd.cc.
References scram::core::SetNode::Ptr().
Referenced by scram::core::zbdd::CutSetContainer::ConvertGate(), FindOrAddVertex(), Minimize(), and Zbdd().
SetNodePtr scram::core::Zbdd::FindOrAddVertex (const Gate & gate, const VertexPtr & high, const VertexPtr & low) protected noexcept
Find or adds a ZBDD SetNode vertex using information from gates.
Parameters
[in] gate Gate with index, order, and other information.
[in] high The new high vertex.
[in] low The new low vertex.
Returns
SetNode for a replacement.
Warning
This function is not aware of reduction rules.
Definition at line 238 of file zbdd.cc.
References Apply(), scram::core::Gate::args(), ClearTables(), scram::core::Gate::coherent(), scram::core::Bdd::Function::complement, FindOrAddVertex(), gates, scram::core::Node::index(), scram::core::Gate::IsConstant(), kBase_, kEmpty_, scram::core::Settings::limit_order(), scram::core::Gate::module(), scram::core::Node::order(), scram::core::NodeParentManager::parents(), scram::core::Settings::prime_implicants(), scram::core::SetNode::Ptr(), scram::core::Terminal< T >::Ptr(), scram::core::Ite::Ptr(), ext::linear_map< Key, Value, ErasePolicy, Sequence >::size(), scram::core::Gate::type(), and scram::core::Bdd::Function::vertex.
Referenced by FindOrAddVertex().
template<Operator Type> VertexPtr scram::core::Zbdd::Apply (const VertexPtr & arg_one, const VertexPtr & arg_two, int limit_order) protected noexcept
Applies Boolean operation to two vertices representing sets.
This is the main function for the operation.
Template Parameters
Type The operator enum.
Parameters
[in] arg_one First argument ZBDD set.
[in] arg_two Second argument ZBDD set.
[in] limit_order The limit on the order for the computations.
Returns
The resulting ZBDD vertex.
Postcondition
The limit on the set order is guaranteed.
Referenced by scram::core::zbdd::CutSetContainer::ConvertGate(), and FindOrAddVertex().
Zbdd::VertexPtr scram::core::Zbdd::Apply (Operator type, const VertexPtr & arg_one, const VertexPtr & arg_two, int limit_order) protected noexcept
Applies Boolean operation to two vertices representing sets.
This is a convenience function if the operator type cannot be determined at compile time.
Parameters
[in] type The operator or type of the gate.
[in] arg_one First argument ZBDD set.
[in] arg_two Second argument ZBDD set.
[in] limit_order The limit on the order for the computations.
Returns
The resulting ZBDD vertex.
Precondition
The operator is either AND or OR.
Postcondition
The limit on the set order is guaranteed.
Definition at line 552 of file zbdd.cc.
References scram::core::kAnd, and scram::core::kOr.
template<Operator Type> VertexPtr scram::core::Zbdd::Apply (const SetNodePtr & arg_one, const SetNodePtr & arg_two, int limit_order) protected noexcept
Applies Boolean operation to ZBDD graph non-terminal vertices.
Template Parameters
Type The operator enum.
Parameters
[in] arg_one First argument set vertex.
[in] arg_two Second argument set vertex.
[in] limit_order The limit on the order for the computations.
Returns
The resulting ZBDD vertex.
Precondition
Argument vertices are ordered.
Zbdd::VertexPtr scram::core::Zbdd::EliminateComplements (const VertexPtr & vertex, std::unordered_map< int, VertexPtr > * wide_results) protected noexcept
Removes complements of variables from products.
This procedure only needs to be performed for non-coherent graphs with minimal cut sets as output.
Parameters
[in] vertex The variable vertex in the ZBDD.
[in,out] wide_results Memoisation of the processed vertices.
Returns
Processed vertex.
Postcondition
Sub-modules are not processed.
Complements of modules are not eliminated.
Definition at line 561 of file zbdd.cc.
References scram::core::Settings::limit_order(), Minimize(), and scram::core::SetNode::Ptr().
Referenced by scram::core::zbdd::CutSetContainer::EliminateComplements(), and Zbdd().
void scram::core::Zbdd::EliminateConstantModules () protected noexcept
Removes constant modules from products.
Constant modules are likely to happen after complement elimination. This procedure is inherently bottom-up, so the caller must make sure that the modules have already been pre-processed.
Precondition
All modules have been processed.
Definition at line 590 of file zbdd.cc.
References scram::DEBUG4, scram::core::Settings::limit_order(), LOG, Minimize(), scram::core::SetNode::Ptr(), and scram::core::Terminal< T >::value().
Referenced by scram::core::zbdd::CutSetContainer::EliminateConstantModules(), and Zbdd().
Zbdd::VertexPtr scram::core::Zbdd::Minimize (const VertexPtr & vertex) protected noexcept
Removes subsets in ZBDD.
Parameters
[in] vertex The variable node in the set.
Returns
Processed vertex.
Definition at line 630 of file zbdd.cc.
References FindOrAddVertex(), kEmpty_, scram::core::Settings::prime_implicants(), scram::core::SetNode::Ptr(), scram::core::Terminal< T >::Ptr(), and scram::core::Terminal< T >::value().
Referenced by Analyze(), Apply(), EliminateComplements(), EliminateConstantModules(), scram::core::zbdd::CutSetContainer::Minimize(), and Zbdd().
int scram::core::Zbdd::GatherModules (const VertexPtr & vertex, int current_order, std::map< int, std::pair< bool, int >> * modules) protected noexcept
Traverses ZBDD to find modules and adjusted cut-offs.
Modules within modules are not gathered.
Parameters
[in] vertex The root vertex to start with.
[in] current_order The product order from the top to the module.
[in,out] modules A map of module indices, coherence, and cut-offs.
Returns
The minimum product order from the bottom.
-1 if the vertex is terminal Empty on low branch only.
Precondition
The ZBDD is minimal.
Definition at line 733 of file zbdd.cc.
References scram::core::Settings::limit_order(), modules(), products(), scram::core::SetNode::Ptr(), scram::core::Terminal< T >::Ptr(), and scram::core::Terminal< T >::value().
Referenced by scram::core::zbdd::CutSetContainer::GatherModules(), and Zbdd().
void scram::core::Zbdd::JoinModule (int index, std::unique_ptr< Zbdd > container) inline protected noexcept
Joins a ZBDD representing a module gate.
Parameters
[in] index The index of the module.
[in] container The container of the module graph.
Precondition
The module products are final, and no more processing or sanitizing is needed.
Definition at line 377 of file zbdd.h.
References scram::core::SetNode::minimal(), and scram::core::SetNode::Ptr().
Referenced by scram::core::zbdd::CutSetContainer::GatherModules(), and Zbdd().
Member Data Documentation
const TerminalPtr scram::core::Zbdd::kBase_ protected
Terminal Base (Unity/1) set.
Todo:
Redesign vertex management and creation.
The management mechanism must be encapsulated. Invariants must be private.
Definition at line 387 of file zbdd.h.
Referenced by Apply(), scram::core::zbdd::CutSetContainer::ConvertGate(), FindOrAddVertex(), and Zbdd().
The documentation for this class was generated from the following files:
zbdd.h
zbdd.cc