scram::core::RiskAnalysis Class Reference
scram::core::RiskAnalysis Class Reference
Main system that performs analyses.
#include <risk_analysis.h>
Public Types
template<class T >
using AnalysisTable = std::map< std::string, std::unique_ptr< T >>
A storage container type for analysis kinds with their ids as keys.
Public Member Functions
RiskAnalysis (std::shared_ptr< const mef::Model > model, const Settings &settings)
const mef::Model & model () const
void Analyze () noexcept
Analyzes the model and performs computations specified in the settings.
const AnalysisTable< FaultTreeAnalysis > & fault_tree_analyses () const
const AnalysisTable< ProbabilityAnalysis > & probability_analyses () const
const AnalysisTable< ImportanceAnalysis > & importance_analyses () const
const AnalysisTable< UncertaintyAnalysis > & uncertainty_analyses () const
Public Member Functions inherited from scram::core::Analysis
Analysis (const Settings &settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Additional Inherited Members
Protected Member Functions inherited from scram::core::Analysis
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Main system that performs analyses.
Definition at line 41 of file risk_analysis.h.
Member Typedef Documentation
template<class T > using scram::core::RiskAnalysis::AnalysisTable = std::map<std::string, std::unique_ptr<T>>
A storage container type for analysis kinds with their ids as keys.
Definition at line 46 of file risk_analysis.h.
Constructor & Destructor Documentation
scram::core::RiskAnalysis::RiskAnalysis (std::shared_ptr< const mef::Model > model, const Settings & settings)
Parameters
[in] model An analysis model with fault trees, events, etc.
[in] settings Analysis settings for the given model.
Definition at line 34 of file risk_analysis.cc.
Member Function Documentation
const mef::Model& scram::core::RiskAnalysis::model () const inline
Returns
The model under analysis.
Definition at line 54 of file risk_analysis.h.
References Analyze().
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
void scram::core::RiskAnalysis::Analyze () noexcept
Analyzes the model and performs computations specified in the settings.
Note
This function must be called only after full initialization of the model with or without its probabilities.
Definition at line 39 of file risk_analysis.cc.
References scram::core::Settings::algorithm(), scram::core::ProbabilityAnalysis::Analyze(), scram::core::UncertaintyAnalysis::Analyze(), scram::core::ImportanceAnalysis::Analyze(), scram::core::FaultTreeAnalyzer< Algorithm >::Analyze(), scram::core::Settings::approximation(), scram::INFO, LOG, scram::Random::seed(), and scram::core::Analysis::settings().
Referenced by model().
const AnalysisTable<FaultTreeAnalysis>& scram::core::RiskAnalysis::fault_tree_analyses () const inline
Returns
Containers of performed analyses identified by the top gate identifiers.
Definition at line 67 of file risk_analysis.h.
Referenced by scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const AnalysisTable<ProbabilityAnalysis>& scram::core::RiskAnalysis::probability_analyses () const inline
Returns
Containers of performed analyses identified by the top gate identifiers.
Definition at line 70 of file risk_analysis.h.
Referenced by scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const AnalysisTable<ImportanceAnalysis>& scram::core::RiskAnalysis::importance_analyses () const inline
Returns
Containers of performed analyses identified by the top gate identifiers.
Definition at line 73 of file risk_analysis.h.
Referenced by scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const AnalysisTable<UncertaintyAnalysis>& scram::core::RiskAnalysis::uncertainty_analyses () const inline
Returns
Containers of performed analyses identified by the top gate identifiers.
Definition at line 76 of file risk_analysis.h.
Referenced by scram::Reporter::Report(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
The documentation for this class was generated from the following files:
risk_analysis.h
risk_analysis.cc