scram::mef::UniformDeviate Class Reference
scram::mef::UniformDeviate Class Reference
Uniform distribution.
#include <random_deviate.h>
Public Member Functions
UniformDeviate (const ExpressionPtr &min, const ExpressionPtr &max)
Setup for uniform distribution.
void Validate () const override
double Mean () noexceptoverride
double Max () noexceptoverride
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::RandomDeviate
bool IsConstant () noexceptoverride
Determines if the value of the expression varies.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args)
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
Uniform distribution.
Definition at line 43 of file random_deviate.h.
Constructor & Destructor Documentation
scram::mef::UniformDeviate::UniformDeviate (const ExpressionPtr & min, const ExpressionPtr & max)
Setup for uniform distribution.
Parameters
[in] min Minimum value of the distribution.
[in] max Maximum value of the distribution.
Definition at line 35 of file random_deviate.cc.
Member Function Documentation
void scram::mef::UniformDeviate::Validate () const override virtual
Exceptions
InvalidArgument The min value is more or equal to max value.
Reimplemented from scram::mef::Expression.
Definition at line 41 of file random_deviate.cc.
References scram::mef::Expression::Max(), scram::mef::Expression::Mean(), scram::mef::Expression::Min(), scram::mef::Expression::Sample(), and scram::Random::UniformRealGenerator().
double scram::mef::UniformDeviate::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 54 of file random_deviate.h.
double scram::mef::UniformDeviate::Max () inline override virtual noexcept
Returns
Maximum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 55 of file random_deviate.h.
double scram::mef::UniformDeviate::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 56 of file random_deviate.h.
The documentation for this class was generated from the following files:
random_deviate.h
random_deviate.cc