scram::mef::Sub Class Reference
scram::mef::Sub Class Reference
This expression performs subtraction operation.
#include <arithmetic.h>
Public Member Functions
double Mean () noexceptoverride
double Max () noexceptoverride
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::BinaryExpression
BinaryExpression (std::vector< ExpressionPtr > args)
Checks the number of provided arguments upon initialization.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args)
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
virtual void Validate () const
Validates the expression.
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual bool IsConstant () noexcept
Determines if the value of the expression varies.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
This expression performs subtraction operation.
First expression minus the rest of the given expressions' values.
Definition at line 90 of file arithmetic.h.
Member Function Documentation
double scram::mef::Sub::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 94 of file arithmetic.h.
References scram::mef::Expression::Mean().
double scram::mef::Sub::Max () inline override virtual noexcept
Returns
Maximum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 95 of file arithmetic.h.
References scram::mef::Expression::Max(), and scram::mef::Expression::Min().
double scram::mef::Sub::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 98 of file arithmetic.h.
References scram::mef::Expression::args(), scram::mef::Expression::Max(), scram::mef::Expression::Min(), and scram::mef::Expression::Sample().
The documentation for this class was generated from the following file:
arithmetic.h