scram::mef::GlmExpression Class Reference
scram::mef::GlmExpression Class Reference
Exponential with probability of failure on demand, hourly failure rate, hourly repairing rate, and time.
#include <exponential.h>
Public Member Functions
GlmExpression (const ExpressionPtr &gamma, const ExpressionPtr &lambda, const ExpressionPtr &mu, const ExpressionPtr &t)
Constructor for GLM or exponential expression with four arguments.
void Validate () const override
Validates the expression.
double Mean () noexceptoverride
double Max () noexceptoverride
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args)
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual bool IsConstant () noexcept
Determines if the value of the expression varies.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
Exponential with probability of failure on demand, hourly failure rate, hourly repairing rate, and time.
Todo:
Find the minimum and maximum values.
Definition at line 70 of file exponential.h.
Constructor & Destructor Documentation
scram::mef::GlmExpression::GlmExpression (const ExpressionPtr & gamma, const ExpressionPtr & lambda, const ExpressionPtr & mu, const ExpressionPtr & t)
Constructor for GLM or exponential expression with four arguments.
Parameters
[in] gamma Probability of failure on demand.
[in] lambda Hourly rate of failure.
[in] mu Hourly repairing rate.
[in] t Mission time in hours.
Definition at line 46 of file exponential.cc.
Member Function Documentation
void scram::mef::GlmExpression::Validate () const override virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
InvalidArgument The arguments are invalid for setup.
Reimplemented from scram::mef::Expression.
Definition at line 56 of file exponential.cc.
References scram::mef::Expression::Max(), scram::mef::Expression::Mean(), and scram::mef::Expression::Min().
double scram::mef::GlmExpression::Mean () override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 76 of file exponential.cc.
References scram::mef::Expression::Mean(), and scram::mef::Expression::Sample().
double scram::mef::GlmExpression::Max () inline override virtual noexcept
Returns
Maximum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 84 of file exponential.h.
double scram::mef::GlmExpression::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 85 of file exponential.h.
The documentation for this class was generated from the following files:
exponential.h
exponential.cc