scram::Reporter Class Reference
scram::Reporter Class Reference
Facilities to report analysis results.
#include <reporter.h>
Public Member Functions
void Report (const core::RiskAnalysis &risk_an, std::ostream &out)
Reports the results of risk analysis on a model.
void Report (const core::RiskAnalysis &risk_an, const std::string &file)
A convenience function to generate the report into a file.
Detailed Description
Facilities to report analysis results.
Definition at line 40 of file reporter.h.
Member Function Documentation
void scram::Reporter::Report (const core::RiskAnalysis & risk_an, std::ostream & out)
Reports the results of risk analysis on a model.
The XML report is formed as a single document.
Parameters
[in] risk_an Risk analysis with results.
[out] out The report destination stream.
Precondition
The output destination is used only by this reporter. There is going to be no appending to the stream after the report.
Definition at line 37 of file reporter.cc.
References scram::XmlStreamElement::AddChild(), CLOCK, scram::DEBUG1, DUR, scram::core::RiskAnalysis::fault_tree_analyses(), scram::core::RiskAnalysis::importance_analyses(), scram::core::Settings::importance_analysis(), LOG, scram::core::RiskAnalysis::probability_analyses(), scram::core::Settings::probability_analysis(), scram::core::Analysis::settings(), scram::core::RiskAnalysis::uncertainty_analyses(), and scram::core::Settings::uncertainty_analysis().
Referenced by Report().
void scram::Reporter::Report (const core::RiskAnalysis & risk_an, const std::string & file)
A convenience function to generate the report into a file.
This function overwrites the file.
Parameters
[in] risk_an Risk analysis with results.
[out] file The output destination.
Exceptions
IOError The output file is not accessible.
Definition at line 64 of file reporter.cc.
References Report().
The documentation for this class was generated from the following files:
reporter.h
reporter.cc