scram::core::ProbabilityAnalyzerBase Class Reference
scram::core::ProbabilityAnalyzerBase Class Reference
Base class for Probability analyzers.
#include <probability_analysis.h>
Public Types
using Product = std::vector< int >
Alias for clarity.
Public Member Functions
template<class Algorithm >
ProbabilityAnalyzerBase (const FaultTreeAnalyzer< Algorithm > *fta)
Constructs probability analyzer from a fault tree analyzer.
const BooleanGraph * graph () const
const std::vector< Product > & products () const
const std::vector< double > & p_vars () const
Public Member Functions inherited from scram::core::ProbabilityAnalysis
ProbabilityAnalysis (const FaultTreeAnalysis *fta)
Probability analysis with the results of qualitative analysis.
void Analyze () noexcept
Performs quantitative analysis on the supplied fault tree.
double p_total () const
Public Member Functions inherited from scram::core::Analysis
Analysis (const Settings &settings)
virtual ~Analysis ()=0
Abstract class.
const Settings & settings () const
const std::string & warnings () const
double analysis_time () const
Additional Inherited Members
Protected Member Functions inherited from scram::core::Analysis
void AddWarning (std::string msg)
Appends a warning message to the analysis warnings.
void AddAnalysisTime (double time)
Adds time to the total analysis time.
Detailed Description
Base class for Probability analyzers.
Definition at line 138 of file probability_analysis.h.
Constructor & Destructor Documentation
template<class Algorithm > scram::core::ProbabilityAnalyzerBase::ProbabilityAnalyzerBase (const FaultTreeAnalyzer< Algorithm > * fta) inline explicit
Constructs probability analyzer from a fault tree analyzer.
Template Parameters
Algorithm Qualitative analysis algorithm.
Parameters
[in] fta Finished fault tree analyzer with results.
Definition at line 148 of file probability_analysis.h.
Member Function Documentation
const BooleanGraph* scram::core::ProbabilityAnalyzerBase::graph () const inline
Returns
The original Boolean graph from the fault tree analyzer.
Definition at line 156 of file probability_analysis.h.
const std::vector<Product>& scram::core::ProbabilityAnalyzerBase::products () const inline
Returns
The resulting products of the fault tree analyzer.
Definition at line 159 of file probability_analysis.h.
Referenced by scram::core::ProbabilityAnalyzer< Calculator >::CalculateTotalProbability().
const std::vector<double>& scram::core::ProbabilityAnalyzerBase::p_vars () const inline
Returns
A mapping for probability values and indices.
Definition at line 162 of file probability_analysis.h.
Referenced by scram::core::ProbabilityAnalyzer< Bdd >::bdd_graph(), scram::core::ProbabilityAnalyzer< Calculator >::CalculateTotalProbability(), and scram::core::ProbabilityAnalyzer< Bdd >::CalculateTotalProbability().
The documentation for this class was generated from the following files:
probability_analysis.h
probability_analysis.cc