scram::mef::Formula Class Reference
scram::mef::Formula Class Reference
Boolean formula with operators and arguments.
#include <event.h>
Public Member Functions
Formula (Operator type)
Constructs a formula.
Operator type () const
int vote_number () const
void vote_number (int number)
Sets the vote number only for an "atleast" formula.
int num_args () const
void AddArgument (FormulaPtr formula)
Adds a formula into the arguments list.
void Validate () const
Checks if a formula is initialized correctly with the number of arguments.
const IdTable< Event * > & event_args () const
const std::vector< HouseEventPtr > & house_event_args () const
const std::vector< BasicEventPtr > & basic_event_args () const
const std::vector< GatePtr > & gate_args () const
const std::vector< FormulaPtr > & formula_args () const
void AddArgument (const HouseEventPtr &event)
Adds an event into the arguments list.
void AddArgument (const BasicEventPtr &event)
Adds an event into the arguments list.
void AddArgument (const GatePtr &event)
Adds an event into the arguments list.
Detailed Description
Boolean formula with operators and arguments.
Formulas are not expected to be shared.
Definition at line 326 of file event.h.
Constructor & Destructor Documentation
scram::mef::Formula::Formula (Operator type) explicit
Constructs a formula.
Parameters
[in] type The logical operator for this Boolean formula.
Definition at line 64 of file event.cc.
Member Function Documentation
Operator scram::mef::Formula::type () const inline
Returns
The type of this formula.
Definition at line 334 of file event.h.
int scram::mef::Formula::vote_number () const
Returns
The vote number if and only if the formula is "atleast".
Exceptions
LogicError The vote number is not yet assigned.
Definition at line 66 of file event.cc.
void scram::mef::Formula::vote_number (int number)
Sets the vote number only for an "atleast" formula.
Parameters
[in] number The vote number.
Exceptions
InvalidArgument The vote number is invalid.
LogicError The vote number is assigned illegally.
Note
(Children number > vote number) should be checked outside of this class.
Definition at line 72 of file event.cc.
References scram::mef::kOperatorToString.
const IdTable<Event*>& scram::mef::Formula::event_args () const inline
Returns
The arguments of this formula of specific type.
Definition at line 354 of file event.h.
const std::vector<HouseEventPtr>& scram::mef::Formula::house_event_args () const inline
Returns
The arguments of this formula of specific type.
Definition at line 355 of file event.h.
const std::vector<BasicEventPtr>& scram::mef::Formula::basic_event_args () const inline
Returns
The arguments of this formula of specific type.
Definition at line 358 of file event.h.
const std::vector<GatePtr>& scram::mef::Formula::gate_args () const inline
Returns
The arguments of this formula of specific type.
Definition at line 361 of file event.h.
Referenced by scram::mef::FaultTree::CollectTopEvents(), and scram::mef::cycle::GetNodes().
const std::vector<FormulaPtr>& scram::mef::Formula::formula_args () const inline
Returns
The arguments of this formula of specific type.
Definition at line 362 of file event.h.
Referenced by scram::mef::FaultTree::CollectTopEvents(), and scram::mef::cycle::GetConnectors().
int scram::mef::Formula::num_args () const inline
Returns
The number of arguments.
Definition at line 366 of file event.h.
Referenced by Validate().
void scram::mef::Formula::AddArgument (const HouseEventPtr & event) inline
Adds an event into the arguments list.
Parameters
[in] event A pointer to an argument event.
Exceptions
DuplicateArgumentError The argument event is duplicate.
Definition at line 375 of file event.h.
Referenced by scram::mef::Initializer::Initializer().
void scram::mef::Formula::AddArgument (const BasicEventPtr & event) inline
Adds an event into the arguments list.
Parameters
[in] event A pointer to an argument event.
Exceptions
DuplicateArgumentError The argument event is duplicate.
Definition at line 378 of file event.h.
void scram::mef::Formula::AddArgument (const GatePtr & event) inline
Adds an event into the arguments list.
Parameters
[in] event A pointer to an argument event.
Exceptions
DuplicateArgumentError The argument event is duplicate.
Definition at line 381 of file event.h.
void scram::mef::Formula::AddArgument (FormulaPtr formula) inline
Adds a formula into the arguments list.
Formulas are unique.
Parameters
[in] formula A pointer to an argument formula.
Definition at line 390 of file event.h.
void scram::mef::Formula::Validate () const
Checks if a formula is initialized correctly with the number of arguments.
Exceptions
ValidationError Problems with the operator or arguments.
Definition at line 87 of file event.cc.
References scram::mef::kOperatorToString, and num_args().
The documentation for this class was generated from the following files:
event.h
event.cc