cycle.h File Reference
cycle.h File Reference
Validation facilities to detect and print cycles in graphs.
#include <string>
#include <vector>
#include "event.h"
#include "parameter.h"
Functions
template<class Ptr >
bool scram::mef::cycle::ContinueConnector (const Ptr &connector, std::vector< std::string > *cycle)
Helper function to check for cyclic references through connectors.
template<class Ptr >
bool scram::mef::cycle::DetectCycle (const Ptr &node, std::vector< std::string > *cycle)
Traverses nodes with connectors to find a cycle.
std::string scram::mef::cycle::PrintCycle (const std::vector< std::string > &cycle)
Prints the detected cycle from the output produced by cycle detection functions.
const Formula * scram::mef::cycle::GetConnector (const GatePtr &node)
Determines the connectors between nodes.
Expression * scram::mef::cycle::GetConnector (Parameter *node)
Determines the connectors between nodes.
const std::vector< GatePtr > & scram::mef::cycle::GetNodes (const FormulaPtr &connector)
Retrieves nodes from a connector.
const std::vector< GatePtr > & scram::mef::cycle::GetNodes (const Formula *connector)
Retrieves nodes from a connector.
std::vector< Parameter * > scram::mef::cycle::GetNodes (Expression *connector)
Retrieves nodes from a connector.
const std::vector< FormulaPtr > & scram::mef::cycle::GetConnectors (const FormulaPtr &connector)
Retrieves connectors from a connector.
const std::vector< FormulaPtr > & scram::mef::cycle::GetConnectors (const Formula *connector)
Retrieves connectors from a connector.
std::vector< Expression * > scram::mef::cycle::GetConnectors (Expression *connector)
Retrieves connectors from a connector.
Detailed Description
Validation facilities to detect and print cycles in graphs.
Definition in file cycle.h.
Function Documentation
const Formula* scram::mef::cycle::GetConnector (const GatePtr & node) inline
Determines the connectors between nodes.
Parameters
[in] node The node under cycle investigation.
Returns
The connector belonging to the node.
Definition at line 41 of file cycle.h.
References scram::mef::cycle::GetConnector().
Referenced by scram::mef::cycle::DetectCycle(), and scram::mef::cycle::GetConnector().
Expression* scram::mef::cycle::GetConnector (Parameter * node) inline
Determines the connectors between nodes.
Parameters
[in] node The node under cycle investigation.
Returns
The connector belonging to the node.
Definition at line 44 of file cycle.h.
References scram::mef::cycle::GetConnector().
const std::vector<GatePtr>& scram::mef::cycle::GetNodes (const FormulaPtr & connector) inline
Retrieves nodes from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of nodes on the other end of connection.
Definition at line 54 of file cycle.h.
References scram::mef::cycle::GetNodes().
Referenced by scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::GetNodes().
const std::vector<GatePtr>& scram::mef::cycle::GetNodes (const Formula * connector) inline
Retrieves nodes from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of nodes on the other end of connection.
Definition at line 57 of file cycle.h.
References scram::mef::Formula::gate_args(), and scram::mef::cycle::GetNodes().
std::vector<Parameter*> scram::mef::cycle::GetNodes (Expression * connector) inline
Retrieves nodes from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of nodes on the other end of connection.
Definition at line 60 of file cycle.h.
References scram::mef::Expression::args(), and scram::mef::cycle::GetNodes().
const std::vector<FormulaPtr>& scram::mef::cycle::GetConnectors (const FormulaPtr & connector) inline
Retrieves connectors from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of connectors.
Definition at line 79 of file cycle.h.
References scram::mef::cycle::GetConnectors().
Referenced by scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::GetConnectors().
const std::vector<FormulaPtr>& scram::mef::cycle::GetConnectors (const Formula * connector) inline
Retrieves connectors from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of connectors.
Definition at line 82 of file cycle.h.
References scram::mef::Formula::formula_args(), and scram::mef::cycle::GetConnectors().
std::vector<Expression*> scram::mef::cycle::GetConnectors (Expression * connector) inline
Retrieves connectors from a connector.
Parameters
[in] connector The connector starting from another node.
Returns
The iterable collection of connectors.
Definition at line 85 of file cycle.h.
References scram::mef::Expression::args(), scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::GetConnectors().
template<class Ptr > bool scram::mef::cycle::ContinueConnector (const Ptr & connector, std::vector< std::string > * cycle)
Helper function to check for cyclic references through connectors.
Connectors may get market upon traversal.
Connectors and nodes of the connector are retrieved via unqualified calls: GetConnectors(connector) and GetNodes(connector).
Template Parameters
Ptr The pointer type managing the connectors (nodes, edges).
Parameters
[in,out] connector Connector to nodes.
[out] cycle The cycle path if detected.
Returns
True if a cycle is detected.
Definition at line 146 of file cycle.h.
References scram::mef::cycle::DetectCycle(), scram::mef::cycle::GetConnectors(), scram::mef::cycle::GetNodes(), and scram::mef::cycle::PrintCycle().
Referenced by scram::mef::cycle::GetConnectors().
template<class Ptr > bool scram::mef::cycle::DetectCycle (const Ptr & node, std::vector< std::string > * cycle)
Traverses nodes with connectors to find a cycle.
Interrupts the detection at first cycle. Nodes get marked.
The connector of the node is retrieved via unqualified call to GetConnector(node).
Template Parameters
Ptr The pointer type managing nodes in the graph.
Parameters
[in,out] node The node to start with.
[out] cycle If a cycle is detected, it is given in reverse, ending with the input node's original name. This is for printing errors and efficiency.
Returns
True if a cycle is found.
Postcondition
All traversed nodes are marked with non-clear marks.
Definition at line 117 of file cycle.h.
References scram::mef::cycle::DetectCycle(), and scram::mef::cycle::GetConnector().
Referenced by scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::DetectCycle().
std::string scram::mef::cycle::PrintCycle (const std::vector< std::string > & cycle)
Prints the detected cycle from the output produced by cycle detection functions.
Parameters
[in] cycle Cycle containing names in reverse order.
Returns
String representation of the cycle.
Definition at line 29 of file cycle.cc.
References scram::mef::cycle::PrintCycle().
Referenced by scram::mef::cycle::ContinueConnector(), and scram::mef::cycle::PrintCycle().