ext.h File Reference
ext.h File Reference
Helpful facilities as an extension to the standard library or Boost.
#include <algorithm>
#include <memory>
#include <boost/range/algorithm/find_if.hpp>
Classes
class ext::find_iterator< Iterator >
Iterator adaptor for indication of container find call results.
Macros
#define CLANG_UNUSED_TYPEDEF_BUG defined(__clang__) && __clang_major__ == 3 && __clang_minor__ == 8
False positive Clang warning in 3.8.
Functions
template<class T , typename... Ts>
auto ext::find (T &&container, Ts &&...args)
Wraps container::find() calls for convenient and efficient lookup with find_iterator adaptor.
template<typename Iterator1 , typename Iterator2 >
bool ext::intersects (Iterator1 first1, Iterator1 last1, Iterator2 first2, Iterator2 last2) noexcept
Determines if two sorted ranges intersect.
template<class SinglePassRange1 , class SinglePassRange2 >
bool ext::intersects (const SinglePassRange1 &rng1, const SinglePassRange2 &rng2)
Range-based version of intersects.
template<typename T >
auto ext::make_unique (T *dumb_handle)
Passes an unmanaged resource to a smart pointer with automatic type deduction.
template<class SinglePassRange , class UnaryPredicate >
bool ext::none_of (const SinglePassRange &rng, UnaryPredicate pred)
Range-based versions of std algorithms missing in Boost.
template<class SinglePassRange , class UnaryPredicate >
bool ext::any_of (const SinglePassRange &rng, UnaryPredicate pred)
Range-based versions of std algorithms missing in Boost.
template<class SinglePassRange , class UnaryPredicate >
bool ext::all_of (const SinglePassRange &rng, UnaryPredicate pred)
Range-based versions of std algorithms missing in Boost.
Detailed Description
Helpful facilities as an extension to the standard library or Boost.
Definition in file ext.h.
Function Documentation
template<class T , typename... Ts> auto ext::find (T && container, Ts &&... args)
Wraps container::find() calls for convenient and efficient lookup with find_iterator adaptor.
Template Parameters
T Container type supporting find() and end() calls.
Ts The argument types to the find() call.
Parameters
[in] container The container to operate upon.
[in] args Arguments to the find() function.
Returns
find_iterator wrapping the resultant iterator.
Definition at line 64 of file ext.h.
References ext::find().
Referenced by ext::find().
template<typename Iterator1 , typename Iterator2 > bool ext::intersects (Iterator1 first1, Iterator1 last1, Iterator2 first2, Iterator2 last2) noexcept
Determines if two sorted ranges intersect.
This function is complementary to std::set_intersection when the actual intersection container is not needed.
Template Parameters
Iterator1 Forward iterator type of the first range.
Iterator2 Forward iterator type of the second range.
Parameters
[in] first1 Start of the first range.
[in] last1 End of the first range.
[in] first2 Start of the second range.
[in] last2 End of the second range.
Returns
true if the [first1, last1) and [first2, last2) ranges intersect.
Definition at line 83 of file ext.h.
References ext::intersects().
Referenced by ext::intersects().
template<typename T > auto ext::make_unique (T * dumb_handle)
Passes an unmanaged resource to a smart pointer with automatic type deduction.
This is a helper function to avoid boilerplate code. This helper would be unnecessary if template arguments could be deduced from constructors.
Parameters
[in] dumb_handle A raw pointer to the resource.
Returns
A smart pointer exclusively owning the resource.
Definition at line 155 of file ext.h.
References ext::make_unique().
Referenced by ext::make_unique().