xml.h File Reference
xml.h File Reference
XML helper facilities to work with libxml++.
#include <memory>
#include <string>
#include <type_traits>
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>
#include <libxml++/libxml++.h>
#include "error.h"
Functions
std::unique_ptr< xmlpp::DomParser > scram::ConstructDomParser (const std::string &file_path)
Initializes a DOM parser and converts library exceptions into local errors.
const xmlpp::Element * scram::XmlElement (const xmlpp::Node *node)
Helper function to statically cast to XML element.
std::string scram::GetAttributeValue (const xmlpp::Element *element, const std::string &attribute_name)
Returns Normalized (trimmed) string value of an XML element attribute.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type scram::CastAttributeValue (const xmlpp::Element *element, const std::string &attribute)
Gets a number from an XML attribute.
std::string scram::GetContent (const xmlpp::TextNode *child_text)
Returns Normalized content of an XML text node.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type scram::CastChildText (const xmlpp::Element *element)
Gets a number from an XML text.
Detailed Description
XML helper facilities to work with libxml++.
Definition in file xml.h.
Function Documentation
std::unique_ptr<xmlpp::DomParser> scram::ConstructDomParser (const std::string & file_path) inline
Initializes a DOM parser and converts library exceptions into local errors.
Parameters
[in] file_path Path to the xml file.
Returns
A parser with a well-formed, initialized document.
Exceptions
ValidationError There are problems loading the XML file.
Definition at line 44 of file xml.h.
References scram::ConstructDomParser().
Referenced by scram::Config::Config(), scram::ConstructDomParser(), and scram::mef::Initializer::Initializer().
const xmlpp::Element* scram::XmlElement (const xmlpp::Node * node) inline
Helper function to statically cast to XML element.
Parameters
[in] node XML node known to be XML element.
Returns
XML element cast from the XML node.
Warning
The node must be an XML element.
Definition at line 60 of file xml.h.
References scram::XmlElement().
Referenced by scram::Config::Config(), scram::mef::Initializer::Initializer(), scram::mef::Initializer::Extractor< T, N >::operator()(), scram::mef::Initializer::Extractor< T,-1 >::operator()(), scram::mef::Initializer::Extractor< Histogram,-1 >::operator()(), and scram::XmlElement().
template<typename T > std::enable_if<std::is_arithmetic<T>::value, T>::type scram::CastAttributeValue (const xmlpp::Element * element, const std::string & attribute)
Gets a number from an XML attribute.
Template Parameters
T Numerical type.
Parameters
[in] element XML element with the attribute.
[in] attribute The name of the attribute.
Returns
The interpreted value.
Exceptions
ValidationError Casting is unsuccessful. The error message will include the line number.
Definition at line 85 of file xml.h.
References scram::CastAttributeValue(), and scram::GetAttributeValue().
Referenced by scram::CastAttributeValue().
template<typename T > std::enable_if<std::is_arithmetic<T>::value, T>::type scram::CastChildText (const xmlpp::Element * element)
Gets a number from an XML text.
Template Parameters
T Numerical type.
Parameters
[in] element XML element with the text.
Returns
The interpreted value.
Exceptions
ValidationError Casting is unsuccessful. The error message will include the line number.
Definition at line 115 of file xml.h.
References scram::CastChildText(), and scram::GetContent().
Referenced by scram::CastChildText().